local GoatQuest=GoatQuest
if not GoatQuest then return end
if GQ:DoMutex("ProfessionsCDRAGON") then return end
GoatQuest.GuideMenuTier = "TRI"
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Artisan's Consortium\\Artisan's Consortium Intro")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Alchemy\\Leveling Guides\\Dragon Isles Alchemy 1-100")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Alchemy\\Leveling Guides\\Dragon Isles Alchemy Knowledge Treasures")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Blacksmithing\\Leveling Guides\\Dragon Isles Blacksmithing 1-100")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Blacksmithing\\Leveling Guides\\Dragon Isles Blacksmithing Knowledge Treasures")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Leveling Guides\\Dragon Isles Cooking 1-100")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Maybe Meat")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Basilisk Eggs")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Bruffalon Flank")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Burly Bear Haunch")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Hornswog Hunk")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Mighty Mammoth Ribs")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Waterfowl Filet")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Enchanting\\Leveling Guides\\Dragon Isles Enchanting 1-100")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Enchanting\\Leveling Guides\\Dragon Isles Enchanting Knowledge Treasures")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Engineering\\Leveling Guides\\Dragon Isles Engineering 1-100")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Engineering\\Leveling Guides\\Dragon Isles Engineering Knowledge Treasures")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Leveling Guides\\Dragon Isles Fishing 1-100")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Ribbed Mollusk Meat")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Aileron Seamoth")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Cerulean Spinefish")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Islefin Dorado")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Lava Beetle")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Magma Thresher")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Thousandbite Piranha")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Temporal Dragonhead")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Scalebelly Mackerel")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Prismatic Leaper")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Rimefin Tuna")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Leveling Guides\\Dragon Isles Herbalism 1-100")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Leveling Guides\\Herbalism Profession Master")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Hochenblume")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Bubble Poppy")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Saxifrage")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Writhebark")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Inscription\\Leveling Guides\\Dragon Isles Inscription 1-100")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Inscription\\Leveling Guides\\Dragon Isles Inscription Knowledge Treasures")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Jewelcrafting\\Leveling Guides\\Dragon Isles Jewelcrafting 1-100")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Jewelcrafting\\Leveling Guides\\Dragon Isles Jewelcrafting Knowledge Treasures")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Leatherworking\\Leveling Guides\\Dragon Isles Leatherworking 1-100")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Leatherworking\\Leveling Guides\\Dragon Isles Leatherworking Knowledge Treasures")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Mining\\Leveling Guides\\Dragon Isles Mining 1-100")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Mining\\Leveling Guides\\Mining Profession Master")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Mining\\Farming Guides\\Rousing Air")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Mining\\Farming Guides\\Rousing Earth")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Mining\\Farming Guides\\Rousing Fire")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Mining\\Farming Guides\\Rousing Frost")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Mining\\Farming Guides\\Serevite")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Mining\\Farming Guides\\Draconium")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Leveling Guides\\Dragon Isles Skinning 1-100")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Farming Guides\\Resilient Leather")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Farming Guides\\Adamant Scales")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Farming Guides\\Dense Hide")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Farming Guides\\Lustrous Scaled Hide")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Leveling Guides\\Skinning Profession Master")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Tailoring\\Leveling Guides\\Dragon Isles Tailoring 1-100")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Tailoring\\Farming Guides\\Tattered Wildercloth")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Tailoring\\Farming Guides\\Wildercloth")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Tailoring\\Leveling Guides\\Dragon Isles Tailoring Knowledge Treasures")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Engineering\\Leveling Guides\\Dragon Isles Engineering Knowledge Treasures")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Jewelcrafting\\Leveling Guides\\Dragon Isles Jewelcrafting Knowledge Treasures")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Leatherworking\\Leveling Guides\\Dragon Isles Leatherworking Knowledge Treasures")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Inscription\\Leveling Guides\\Dragon Isles Inscription Knowledge Treasures")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Enchanting\\Leveling Guides\\Dragon Isles Enchanting Knowledge Treasures")
