local GoatQuest=GoatQuest
if not GoatQuest then return end
if UnitFactionGroup("player")~="Horde" then return end
if GQ:DoMutex("ProfessionsHLEGION") then return end
GoatQuest.GuideMenuTier = "TRI"
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Alchemy\\Leveling Guides\\Legion Alchemy 1-100")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Alchemy\\Quest Guides\\Legion Alchemy Quest Line")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Alchemy\\Quest Guides\\Argus Alchemy Quest Line")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Archaeology\\Leveling Guides\\Archaeology 700-800")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Archaeology\\Quest Guides\\Legion Archaeology Quest Line")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Blacksmithing\\Leveling Guides\\Legion Blacksmithing 1-100")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Blacksmithing\\Quest Guides\\Legion Blacksmithing Quest Line")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Blacksmithing\\Quest Guides\\Argus Blacksmithing Quest Line")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Big Gamy Ribs")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Fatty Bearsteak")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Lean Shank")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Leyblood")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Wildfowl Egg")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Leveling Guides\\Legion Cooking 1-100")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Quest Guides\\Legion Cooking Quest Line")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Big Gamy Ribs")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Fatty Bearsteak")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Lean Shank")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Leyblood")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Wildfowl Egg")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Enchanting\\Leveling Guides\\Legion Enchanting 1-100")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Enchanting\\Quest Guides\\Legion Enchanting Quest Line")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Engineering\\Leveling Guides\\Legion Engineering 1-100")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Engineering\\Quest Guides\\Legion Engineering Quest Line")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Engineering\\Quest Guides\\Argus Engineering Quest Line")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Leveling Guides\\Legion Fishing 1-100")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Black Barracuda")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Highmountain Salmon")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Silver Mackerel")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Quest Guides\\Legion Fishing Quest Line")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Quest Guides\\Underlight Angler (Legion Fishing Artifact)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Black Barracuda")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Highmountain Salmon")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Silver Mackerel")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Leveling Guides\\Legion Herbalism 1-100")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Aethril")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Astral Glory")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Dreamleaf")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Felwort")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Fjarnskaggl")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Foxflower")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Starlight Rose")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Quest Guides\\Legion Herbalism Quest Line")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Quest Guides\\Argus Herbalism Quest Line")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Aethril")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Astral Glory")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Dreamleaf")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Felwort")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Fjarnskaggl")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Foxflower")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Starlight Rose")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Inscription\\Leveling Guides\\Legion Inscription 1-100")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Inscription\\Quest Guides\\Legion Inscription Quest Line")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Jewelcrafting\\Leveling Guides\\Legion Jewelcrafting 1-100")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Jewelcrafting\\Quest Guides\\Legion Jewelcrafting Quest Line")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Jewelcrafting\\Quest Guides\\Argus Jewelcrafting Quest Line")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Leatherworking\\Leveling Guides\\Legion Leatherworking 1-100")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Leatherworking\\Quest Guides\\Legion Leatherworking Quest Line")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Leatherworking\\Quest Guides\\Argus Leatherworking Quest Line")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Mining\\Farming Guides\\Empyrium")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Mining\\Farming Guides\\Felslate")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Mining\\Farming Guides\\Leystone")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Mining\\Leveling Guides\\Legion Mining 1-100")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Mining\\Quest Guides\\Legion Mining Quest Line")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Mining\\Quest Guides\\Argus Mining Quest Line")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Mining\\Farming Guides\\Empyrium")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Mining\\Farming Guides\\Felslate")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Mining\\Farming Guides\\Leystone")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Leveling Guides\\Legion Skinning 1-100")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Quest Guides\\Legion Skinning Quest Line")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Quest Guides\\Argus Skinning Quest Line")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Farming Guides\\Fiendish Leather")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Farming Guides\\Stonehide Leather")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Farming Guides\\Stormscale")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Tailoring\\Leveling Guides\\Legion Tailoring 1-100")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Tailoring\\Farming Guides\\Lightweave Cloth")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Tailoring\\Farming Guides\\Shal'dorei Silk")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Tailoring\\Quest Guides\\Legion Tailoring Quest Line")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Tailoring\\Quest Guides\\Argus Tailoring Quest Line")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Tailoring\\Farming Guides\\Lightweave Cloth")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Tailoring\\Farming Guides\\Shal'dorei Silk")
