local GoatQuest=GoatQuest
if not GoatQuest then return end
if GQ:DoMutex("ProfessionsCMoP") then return end
GoatQuest.GuideMenuTier = "TRI"
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Alchemy\\Leveling Guides\\Pandaria Alchemy 1-75")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Daily Guides\\Pandaria Cooking Daily Guide")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Leveling Guides\\Pandaria Cooking 1-75")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Leveling Guides\\Pandaria Way of the Brew 1-75")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Leveling Guides\\Pandaria Way of the Grill 1-75")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Leveling Guides\\Pandaria Way of the Oven 1-75")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Leveling Guides\\Pandaria Way of the Pot 1-75")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Leveling Guides\\Pandaria Way of the Steamer 1-75")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Leveling Guides\\Pandaria Way of the Wok 1-75")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Enchanting\\Leveling Guides\\Pandaria Enchanting 1-75")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Engineering\\Leveling Guides\\Pandaria Engineering 1-75")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Jade Lungfish")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Krasarang Paddlefish")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Redbelly Mandarin")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Giant Mantis Shrimp")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Emperor Salmon")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Golden Carp")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Spinefish")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Reef Octopus")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Tiger Gourami")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Jewel Danio")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Fool's Cap")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Golden Lotus")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Green Tea Leaf")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Rain Poppy")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Silkweed")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Snow Lily")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Inscription\\Leveling Guides\\Pandaria Inscription 1-75")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Jewelcrafting\\Leveling Guides\\Pandaria Jewelcrafting 1-75")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Leatherworking\\Leveling Guides\\Pandaria Leatherworking 1-75")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Mining\\Farming Guides\\Ghost Iron")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Mining\\Farming Guides\\Kyparite")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Mining\\Farming Guides\\Trillium")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Farming Guides\\Exotic Leather")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Leveling Guides\\Pandaria Skinning 1-75")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Farming Guides\\Exotic Leather")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\General Farming Guides\\Spirit of Harmony")
