local GoatQuest=GoatQuest
if not GoatQuest then return end
if GQ:DoMutex("ProfessionsCSHADOW") then return end
GoatQuest.GuideMenuTier = "TRI"
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Alchemy\\Leveling Guides\\Shadowlands Alchemy 1-175")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Blacksmithing\\Leveling Guides\\Shadowlands Blacksmithing 1-100")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Leveling Guides\\Shadowlands Cooking 1-75")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Aethereal Meat (Bastion)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Aethereal Meat (Revendreth)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Creeping Crawler Meat (Maldraxxus)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Creeping Crawler Meat (Ardenweald)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Phantasmal Haunch (Ardenweald)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Phantasmal Haunch (Maldraxxus)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Raw Seraphic Wing")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Shadowy Shank (Ardenweald)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Shadowy Shank (Maldraxxus)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Tenebrous Ribs (Maldraxxus)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Tenebrous Ribs (Ardenweald)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Iridescent Amberjack")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Lost Sole")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Pocked Bonefish")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Silvergill Pike")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Spinefin Piranha")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Elysian Thade")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Enchanting\\Leveling Guides\\Shadowlands Enchanting 1-115")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Engineering\\Leveling Guides\\Shadowlands Engineering 1-100")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Leveling Guides\\Shadowlands Fishing 1-200")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Iridescent Amberjack")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Lost Sole")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Pocked Bonefish")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Silvergill Pike")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Spinefin Piranha")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Elysian Thade")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Leveling Guides\\Shadowlands Herbalism 1-150")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Death Blossom")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Marrowroot")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Vigil's Torch")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Rising Glory")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Widowbloom")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Nightshade")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\First Flower")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Inscription\\Leveling Guides\\Shadowlands Inscription 1-100")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Jewelcrafting\\Leveling Guides\\Shadowlands Jewelcrafting 1-100")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Leatherworking\\Leveling Guides\\Shadowlands Leatherworking 1-100")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Mining\\Leveling Guides\\Shadowlands Mining 1-150")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Mining\\Farming Guides\\Elethium Ore")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Mining\\Farming Guides\\Laestrite Ore")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Mining\\Farming Guides\\Oxxein Ore")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Mining\\Farming Guides\\Phaedrum Ore")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Mining\\Farming Guides\\Sinvyr Ore")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Mining\\Farming Guides\\Solenium Ore")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Mining\\Farming Guides\\Progenium Ore")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Leveling Guides\\Shadowlands Skinning 1-150")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Farming Guides\\Callous Hide (Bastion)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Farming Guides\\Callous Hide (Ardenweald)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Farming Guides\\Callous Hide (Maldraxxus)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Farming Guides\\Desolate Leather (Bastion)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Farming Guides\\Desolate Leather (Ardenweald)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Farming Guides\\Desolate Leather (Maldraxxus)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Farming Guides\\Heavy Callous Hide (Bastion)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Farming Guides\\Heavy Callous Hide (Ardenweald)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Farming Guides\\Heavy Callous Hide (Maldraxxus)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Farming Guides\\Heavy Desolate Leather (Bastion)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Farming Guides\\Heavy Desolate Leather (Ardenweald)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Farming Guides\\Heavy Desolate Leather (Maldraxxus)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Farming Guides\\Pallid Bone (Bastion)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Farming Guides\\Pallid Bone (Ardenweald)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Farming Guides\\Pallid Bone (Maldraxxus)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Tailoring\\Leveling Guides\\Shadowlands Tailoring 1-100")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Tailoring\\Farming Guides\\Lightless Silk (Ardenweald)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Tailoring\\Farming Guides\\Lightless Silk (Revendreth)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Tailoring\\Farming Guides\\Shrouded Cloth (Ardenweald)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Tailoring\\Farming Guides\\Shrouded Cloth (Revendreth)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Bronze Helicid")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Bronzewing Vespoid")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Buzz")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Deathrunner")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Forged Spiteflyer")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Genesis Crawler")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Heartbond Lupine")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Pale Regal Cervid")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Raptora Swooper")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Russet Bufonid")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Sundered Zerethsteed")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Tarachnid Creeper")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Vespoid Flutterer")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Ambystan Darter")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Archetype of Metamorphosis")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Archetype of Renewal")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Archetype of Serenity")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Prototickles")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Terror Jelly")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Archetype of Cunning")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Archetype of Discovery")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Archetype of Predation")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Tunneling Vombata")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Viperid Menace")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Archetype of Multiplicity")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Archetype of Survival")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Archetype of Vigilance")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Fierce Scarabid")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Leaping Leporid")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Shelly")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Archetype of Animation")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Stabilized Geomental")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Archetype of Malice")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Archetype of Motion")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Archetype of Satisfaction")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Multichicken")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Violent Poultrid")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Archetype of Focus")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Omnipotential Core")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Resonant Echo")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Protoform Synthesis\\Schematic: Adorned Vombata")
