local GoatQuest=GoatQuest
if not GoatQuest then return end
if GQ:DoMutex("ProfessionsCTWW") then return end
GoatQuest.GuideMenuTier = "TRI"
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Alchemy\\Leveling Guides\\Khaz Algar Alchemy 1-100")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Alchemy\\Khaz Algar Alchemy Knowledge Treasures")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Blacksmithing\\Leveling Guides\\Khaz Algar Blacksmithing 1-100")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Blacksmithing\\Khaz Algar Blacksmithing Knowledge Treasures")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Leveling Guides\\Khaz Algar Cooking 1-100")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Enchanting\\Leveling Guides\\Khaz Algar Enchanting 1-100")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Enchanting\\Khaz Algar Enchanting Knowledge Treasures")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Engineering\\Leveling Guides\\Khaz Algar Engineering 1-100")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Engineering\\Khaz Algar Engineering Knowledge Treasures")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Leveling Guides\\Khaz Algar Fishing 1-100")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Cursed Ghoulfish")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Bismuth Bitterling")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Crystalline Sturgeon")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Dornish Pike")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Specular Rainbowfish")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Whispering Stargazer")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Spiked Sea Raven")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Goldengill Trout")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Nibbling Minnow")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Quiet River Bass")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Roaring Anglerseeker")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Queen's Lurefish")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Regal Dottyback")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Awoken Coelacanth")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Arathor Hammerfish")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Bloody Perch")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Dilly-Dally Dace")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Kaheti Slum Shark")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Pale Huskfish")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Sanguine Dogfish")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Leveling Guides\\Khaz Algar Herbalism 1-100")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Khaz Algar Herbalism Knowledge Treasures")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Mycobloom (Azj-Kahet)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Mycobloom (Hallowfall)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Mycobloom (Isle of Dorn)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Mycobloom (The Ringing Deeps)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Arathor's Spear (Hallowfall)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Arathor's Spear (The Ringing Deeps)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Blessing Blossom (Hallowfall)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Blessing Blossom (The Ringing Deeps)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Blessing Blossom (Isle of Dorn)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Orbinid (Azj-Kahet)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Orbinid (The Ringing Deeps)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Luredrop (Azj-Kahet)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Luredrop (The Ringing Deeps)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Inscription\\Leveling Guides\\Khaz Algar Inscription 1-100")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Inscription\\Khaz Algar Inscription Knowledge Treasures")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Jewelcrafting\\Leveling Guides\\Khaz Algar Jewelcrafting 1-100")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Jewelcrafting\\Khaz Algar Jewelcrafting Knowledge Treasures")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Leatherworking\\Leveling Guides\\Khaz Algar Leatherworking 1-100")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Leatherworking\\Khaz Algar Leatherworking Knowledge Treasures")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Mining\\Leveling Guides\\Khaz Algar Mining 1-100")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Mining\\Farming Guides\\Bismuth (Azj-Kahet)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Mining\\Khaz Algar Mining Knowledge Treasures")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Mining\\Farming Guides\\Bismuth (Hallowfall)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Mining\\Farming Guides\\Bismuth (Isle of Dorn)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Mining\\Farming Guides\\Bismuth (The Ringing Deeps)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Mining\\Farming Guides\\Ironclaw (Isle of Dorn)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Mining\\Farming Guides\\Ironclaw (The Ringing Deeps)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Mining\\Farming Guides\\Aqirite (Azj-Kahet)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Mining\\Farming Guides\\Aqirite (Hallowfall)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Leveling Guides\\Khaz Algar Skinning 1-100")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Farming Guides\\Stormcharged Leather (Isle of Dorn)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Khaz Algar Skinning Knowledge Treasures")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Farming Guides\\Stormcharged Leather (Isle of Dorn)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Farming Guides\\Thunderous Hide (Isle of Dorn)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Farming Guides\\Gloom Chitin (Azj-Kahet)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Farming Guides\\Sunless Carapace (Azj-Kahet)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Tailoring\\Leveling Guides\\Khaz Algar Tailoring 1-100")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Tailoring\\Khaz Algar Tailoring Knowledge Treasures")
