local GoatQuest=GoatQuest
if not GoatQuest then return end
if UnitFactionGroup("player")~="Alliance" then return end
if GQ:DoMutex("ProfessionsABFA") then return end
GoatQuest.GuideMenuTier = "TRI"
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Alchemy\\Leveling Guides\\Kul Tiran Alchemy 1-175")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Alchemy\\Leveling Guides\\Tools of the Trade - Alchemy")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Archaeology\\Leveling Guides\\Archaeology 800-950")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Blacksmithing\\Leveling Guides\\Kul Tiran Blacksmithing 1-175")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Blacksmithing\\Leveling Guides\\Tools of the Trade - Blacksmithing")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Leveling Guides\\Kul Tiran Cooking 1-175")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Aberrant Voidfin")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Briny Flesh")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Malformed Gnasher")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Meaty Haunch")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Moist Fillet")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Questionable Meat")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Rubbery Flank")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Stringy Loins")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Cooking\\Farming Guides\\Thick Paleo Steak")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Enchanting\\Leveling Guides\\Kul Tiran Enchanting 1-175")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Enchanting\\Leveling Guides\\Tools of the Trade - Enchanting")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Engineering\\Leveling Guides\\Kul Tiran Engineering 1-175")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Engineering\\Leveling Guides\\Tools of the Trade - Engineering")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Leveling Guides\\Kul Tiran Fishing 1-175")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Aromatic Fish Oil")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Frenzied Fangtooth")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Great Sea Catfish")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Ionized Minnow")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Lane Snapper")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Mauve Stinger")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Midnight Salmon")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Redtail Loach")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Sand Shifter")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Slimy Mackerel")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Tiragarde Perch")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Viper Fish")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Fishing\\Farming Guides\\Mauve Stinger")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Leveling Guides\\Kul Tiran Herbalism 1-175")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Quest Guides\\Kul Tiran Herbalism Quest Line")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Akunda's Bite")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Anchor Weed")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Riverbud")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Sea Stalk")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Siren's Pollen")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Star Moss")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Winter's Kiss")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Herbalism\\Farming Guides\\Zin'anthid")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Inscription\\Leveling Guides\\Kul Tiran Inscription 1-175")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Inscription\\Leveling Guides\\Tools of the Trade - Inscription")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Jewelcrafting\\Leveling Guides\\Kul Tiran Jewelcrafting 1-175")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Jewelcrafting\\Leveling Guides\\Tools of the Trade - Jewelcrafting")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Leatherworking\\Leveling Guides\\Kul Tiran Leatherworking 1-175")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Leatherworking\\Leveling Guides\\Tools of the Trade - Leatherworking")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Mining\\Leveling Guides\\Kul Tiran Mining 1-175")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Mining\\Quest Guides\\Kul Tiran Mining Quest Line")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Mining\\Farming Guides\\Monelite (Stormsong Valley)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Mining\\Farming Guides\\Monelite (Vol'dun)")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Mining\\Farming Guides\\Osmenite Ore")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Mining\\Farming Guides\\Platinum Ore")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Mining\\Farming Guides\\Storm Silver Ore")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Leveling Guides\\Kul Tiran Skinning 1-175")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Quest Guides\\Kul Tiran Skinning Quest Guide")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Farming Guides\\Blood-Stained Bone")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Farming Guides\\Calcified Bone")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Farming Guides\\Coarse Leather")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Farming Guides\\Dredged Leather")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Farming Guides\\Mistscale")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Farming Guides\\Shimmerscale")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Skinning\\Farming Guides\\Tempest Hide")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Tailoring\\Leveling Guides\\Kul Tiran Tailoring 1-175")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Tailoring\\Leveling Guides\\Tools of the Trade - Tailoring")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Tailoring\\Farming Guides\\Deep Sea Satin")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Tailoring\\Farming Guides\\Gilded Seaweave")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\Tailoring\\Farming Guides\\Tidespray Linen")
GoatQuest:RegisterGuidePlaceholder("Profession Guides\\General Farming Guides\\Void Focus")
