local GoatQuest=GoatQuest
if not GoatQuest then return end
if UnitFactionGroup("player")~="Alliance" then return end
if GQ:DoMutex("TitlesAMOP") then return end
GoatQuest.GuideMenuTier = "TRI"
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\Dungeons & Raids\\The Bloodseeker")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\Dungeons & Raids\\Conqurer of Orgrimmar")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\Dungeons & Raids\\Darkmaster")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\Dungeons & Raids\\Defender of the Wall")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\Dungeons & Raids\\Delver of the Vaults")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\Dungeons & Raids\\The Dissector")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\Dungeons & Raids\\The Fearless")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\Dungeons & Raids\\Flameweaver")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\Dungeons & Raids\\Hellscream's Downfall")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\Dungeons & Raids\\Jade Protector")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\Dungeons & Raids\\The Locust")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\Dungeons & Raids\\The Lucid")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\Dungeons & Raids\\The Manipulator")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\Dungeons & Raids\\Mistwalker")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\Dungeons & Raids\\Mogu-Slayer")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\Dungeons & Raids\\The Poisoned Mind")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\Dungeons & Raids\\The Prime")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\Dungeons & Raids\\Purified Defender")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\Dungeons & Raids\\Scarab Lord")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\Dungeons & Raids\\Scarlet Commander")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\Dungeons & Raids\\Siegebreaker")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\Dungeons & Raids\\Storm's End")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\Dungeons & Raids\\The Swarmkeeper")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\Dungeons & Raids\\Undaunted")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\Dungeons & Raids\\The Wind-Reaver")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\General\\The Proven Assailant")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\General\\The Proven Defender")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\General\\The Proven Healer")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\General\\The Relic Hunter")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\General\\Shado-Master")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\General\\The Stormbreaker")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\Player versus Player\\Fire-Watcher")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\Player versus Player\\Gorgeous")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\Player versus Player\\Grievous Gladiator")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\Player versus Player\\Khan")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\Player versus Player\\Malevolent Gladiator")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\Player versus Player\\Prideful Gladiator")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\Player versus Player\\Tyrannical Gladiator")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\Pet Battles\\Crazy Cat Lady/Man")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\Pet Battles\\Tamer")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\Pet Battles\\Trainer")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\Pet Battles\\Zookeeper")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\Quests\\Of The Iron Vanguard")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\Quests\\Legend of Pandaria")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\Quests\\Stormbreaker")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\Professions\\Cooking\\Master of the Ways")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\Reputations\\The Beloved")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\Reputations\\Farmer")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\Reputations\\The Wakener")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\Scenarios\\Of the Black Harvest")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\Scenarios\\Scenaturdist")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\World Events\\Brawler")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Mists of Pandaria Titles\\World Events\\The Hordebreaker")
