local GoatQuest=GoatQuest
if not GoatQuest then return end
if UnitFactionGroup("player")~="Horde" then return end
if GQ:DoMutex("TitlesHWOD") then return end
GoatQuest.GuideMenuTier = "TRI"
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Warlords of Draenor Titles\\Dungeons & Raids\\Defiler's End")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Warlords of Draenor Titles\\Dungeons & Raids\\Dockmaster")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Warlords of Draenor Titles\\Dungeons & Raids\\Empire's Twilight")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Warlords of Draenor Titles\\Dungeons & Raids\\Grimrail Suplexer")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Warlords of Draenor Titles\\Dungeons & Raids\\The Indomitable")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Warlords of Draenor Titles\\Dungeons & Raids\\Ironbane")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Warlords of Draenor Titles\\Dungeons & Raids\\Lord/Lady of Blackrock")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Warlords of Draenor Titles\\Dungeons & Raids\\The Mine Master")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Warlords of Draenor Titles\\Dungeons & Raids\\Savage Hero")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Warlords of Draenor Titles\\Dungeons & Raids\\Scion of Rukhmar")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Warlords of Draenor Titles\\Dungeons & Raids\\Soul Preserver")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Warlords of Draenor Titles\\Dungeons & Raids\\Spiritwalker")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Warlords of Draenor Titles\\Dungeons & Raids\\Violet Guardian")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Warlords of Draenor Titles\\Garrisons\\Architect")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Warlords of Draenor Titles\\Garrisons\\Captain")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Warlords of Draenor Titles\\Garrisons\\Draenei Destroyer")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Warlords of Draenor Titles\\Garrisons\\Dwarfstalker")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Warlords of Draenor Titles\\Garrisons\\Gnomebane")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Warlords of Draenor Titles\\Garrisons\\Lord/Lady of War")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Warlords of Draenor Titles\\Garrisons\\Lumberjack")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Warlords of Draenor Titles\\Garrisons\\Manslayer")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Warlords of Draenor Titles\\Garrisons\\Scourge of the Kaldorei")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Warlords of Draenor Titles\\Garrisons\\Stable Master")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Warlords of Draenor Titles\\Garrisons\\Terror of the Tushui")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Warlords of Draenor Titles\\Garrisons\\Timber Lord")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Warlords of Draenor Titles\\Garrisons\\Warlord of Draenor")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Warlords of Draenor Titles\\Garrisons\\Worgen Hunter")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Warlords of Draenor Titles\\General\\Field Photographer")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Warlords of Draenor Titles\\General\\Jenkins")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Warlords of Draenor Titles\\General\\Predator")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Warlords of Draenor Titles\\Player versus Player\\Defender of the Horde")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Warlords of Draenor Titles\\Player versus Player\\Guardian of the Horde")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Warlords of Draenor Titles\\Player versus Player\\Primal Gladiator")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Warlords of Draenor Titles\\Player versus Player\\Soldier of the Horde")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Warlords of Draenor Titles\\Player versus Player\\Warmongering Gladiator")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Warlords of Draenor Titles\\Player versus Player\\Wild Gladiator")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Warlords of Draenor Titles\\Professions\\Artisan")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Warlords of Draenor Titles\\Quests\\Blood Champion")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Warlords of Draenor Titles\\Quests\\of the Jungle")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Warlords of Draenor Titles\\Reputations\\Conservationist")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Warlords of Draenor Titles\\Reputations\\of the Frostwolves")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Warlords of Draenor Titles\\Reputations\\Masked Chuckler")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Warlords of Draenor Titles\\Reputations\\Spear of Vol'jin")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Warlords of Draenor Titles\\Reputations\\Talon King/Queen")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Warlords of Draenor Titles\\World Events\\Southshore Slayer")
