local GoatQuest=GoatQuest
if not GoatQuest then return end
if UnitFactionGroup("player")~="Alliance" then return end
if GQ:DoMutex("TitlesALEGION") then return end
GoatQuest.GuideMenuTier = "TRI"
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Legion Titles\\Class Halls\\Archdruid")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Legion Titles\\Class Halls\\Archmage")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Legion Titles\\Class Halls\\Battlelord")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Legion Titles\\Class Halls\\Deathlord")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Legion Titles\\Class Halls\\Farseer")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Legion Titles\\Class Halls\\Grandmaster")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Legion Titles\\Class Halls\\Guardian of G'Hanir")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Legion Titles\\Class Halls\\High Priest")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Legion Titles\\Class Halls\\Highlord")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Legion Titles\\Class Halls\\Huntmaster")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Legion Titles\\Class Halls\\The Illidari")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Legion Titles\\Class Halls\\Netherlord")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Legion Titles\\Class Halls\\Shadowblade")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Legion Titles\\Class Halls\\Slayer")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Legion Titles\\Dungeons & Raids\\The Chosen")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Legion Titles\\Dungeons & Raids\\The Darkener")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Legion Titles\\Dungeons & Raids\\The Dreamer")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Legion Titles\\Dungeons & Raids\\The Tomb Raider")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Legion Titles\\Dungeons & Raids\\Vengeance Incarnate")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Legion Titles\\General\\Crashin' Thrashin'")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Legion Titles\\General\\The Fabulous")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Legion Titles\\General\\The Gullible")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Legion Titles\\General\\Legionary")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Legion Titles\\General\\Lord of the Reins")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Legion Titles\\General\\Postmaster")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Legion Titles\\General\\Stylist")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Legion Titles\\General\\Timelord")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Legion Titles\\Player versus Player\\Fearless Gladiator")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Legion Titles\\Player versus Player\\Patron of War")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Legion Titles\\Player versus Player\\Vindictive Gladiator")
GoatQuest:RegisterGuidePlaceholder("Title Guides\\Legion Titles\\Professions\\Archaeology\\The Groundbreaker")
