local GoatQuest=GoatQuest
if not GoatQuest then return end
if GQ:DoMutex("DailiesCDRAGON") then return end
GoatQuest.GuideMenuTier = "TRI"
GoatQuest:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\The Azure Span World Quests")
GoatQuest:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\The Emerald Dream World Quests")
GoatQuest:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\The Forbidden Reach World Quests")
GoatQuest:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\Ohn'ahran Plains World Quests")
GoatQuest:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\Thaldraszus World Quests")
GoatQuest:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\The Waking Shores World Quests")
GoatQuest:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\Zaralek Cavern World Quests")
GoatQuest:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\Dragonscale Expedition\\Dragonscale Basecamp Weekly Quests")
GoatQuest:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\Iskaara Tuskarr\\Grimtusk's Fishing Hole")
GoatQuest:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\Iskaara Tuskarr\\River Mouth Fishing Hole")
GoatQuest:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\Iskaara Tuskarr\\Tyrhold Fishing Hole")
GoatQuest:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\Iskaara Tuskarr\\Roaring Dragonspring Fishing Hole")
GoatQuest:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\Maruuk Centaur\\Aylaag Outpost Daily Quests (Rusza'thar Reach)")
GoatQuest:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\Maruuk Centaur\\Aylaag Outpost Daily Quests (Pinewood Post)")
GoatQuest:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\Maruuk Centaur\\Aylaag Outpost Daily Quests (Eaglewatch Outpost)")
GoatQuest:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\The Obsidian Citadel Weekly Quests")
GoatQuest:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\Siege on Dragonbane Keep")
GoatQuest:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\A Cataloger's Paradise")
GoatQuest:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\A Climber's Calling")
GoatQuest:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\Dragon Isles Emissary")
GoatQuest:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\Forbidden Reach Envoy Dailies")
GoatQuest:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\Iskaara Tuskarr\\Dragonskull Island Fishing Hole")
GoatQuest:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\Sniffenseeking!")
GoatQuest:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\Snail Racing Dailies")
GoatQuest:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\Suffusion Camp (Ohn'ahran Plains)")
GoatQuest:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\Suffusion Camp (The Azure Span)")
GoatQuest:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\Researchers Under Fire")
GoatQuest:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\Time Rifts")
GoatQuest:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\Little Scales Daycare")
GoatQuest:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\Eon's Fringe Dailies")
GoatQuest:RegisterGuidePlaceholder("Daily Guides\\Dragonflight (10-70)\\Little Scales Daycare Dailies")
