local GoatQuest=GoatQuest
if not GoatQuest then return end
if GQ:DoMutex("EventsC") then return end
GoatQuest.GuideMenuTier = "TRI"
GoatQuest:RegisterGuidePlaceholder("Events Guides\\Midnight (80-90)\\Curse Surges\\The Broodmother's Nest")
GoatQuest:RegisterGuidePlaceholder("Events Guides\\Midnight (80-90)\\Curse Surges\\The Malformed Leviathan")
GoatQuest:RegisterGuidePlaceholder("Events Guides\\Midnight (80-90)\\Curse Surges\\Mlurkkr Massacre")
GoatQuest:RegisterGuidePlaceholder("Events Guides\\Midnight (80-90)\\Curse Surges\\Siege at the Whispering Marsh")
GoatQuest:RegisterGuidePlaceholder("Events Guides\\Midnight (80-90)\\Curse Surges\\The Looming Mutagenitor")
GoatQuest:RegisterGuidePlaceholder("Events Guides\\Midnight (80-90)\\The Vaults of Atal'Utek")
GoatQuest:RegisterGuidePlaceholder("Events Guides\\Midnight (80-90)\\Eversong Woods Void Assaults")
GoatQuest:RegisterGuidePlaceholder("Events Guides\\Midnight (80-90)\\Zul'Aman Void Assaults")
GoatQuest:RegisterGuidePlaceholder("Events Guides\\Midnight (80-90)\\Eversong Woods Ritual Site")
GoatQuest:RegisterGuidePlaceholder("Events Guides\\Midnight (80-90)\\Zul'Aman Ritual Site")
GoatQuest:RegisterGuidePlaceholder("Events Guides\\Midnight (80-90)\\Abyss Anglers")
GoatQuest:RegisterGuidePlaceholder("Events Guides\\Brewfest\\A Round on the House in Midnight")
GoatQuest:RegisterGuidePlaceholder("Events Guides\\Dragonflight (10-70)\\Azerothian Archives!")
GoatQuest:RegisterGuidePlaceholder("Events Guides\\Dragonflight (10-70)\\The Big Dig: Traitor's Rest")
GoatQuest:RegisterGuidePlaceholder("Events Guides\\Dragonflight (10-70)\\Emerald Dreamsurge (Thaldraszus)")
GoatQuest:RegisterGuidePlaceholder("Events Guides\\Dragonflight (10-70)\\Emerald Dreamsurge (The Waking Shores)")
GoatQuest:RegisterGuidePlaceholder("Events Guides\\Dragonflight (10-70)\\Emerald Dreamsurge (Ohn'ahran Plains)")
GoatQuest:RegisterGuidePlaceholder("Events Guides\\Dragonflight (10-70)\\Emerald Dreamsurge (The Azure Span)")
GoatQuest:RegisterGuidePlaceholder("Events Guides\\Secrets of Azeroth\\Secrets of Azeroth")
GoatQuest:RegisterGuidePlaceholder("Events Guides\\Secrets of Azeroth\\Community Rumors")
GoatQuest:RegisterGuidePlaceholder("Events Guides\\Secrets of Azeroth\\Secrets of Azeroth Mimiron's Jumpjets Mount")
GoatQuest:RegisterGuidePlaceholder("Events Guides\\Dragonflight (10-70)\\The Emerald Dream Superbloom")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Incognitro, the Indecipherable Felcycle")
GoatQuest:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\Revisited Horrific Vision of Orgrimmar")
GoatQuest:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\Revisited Horrific Vision of Stormwind")
GoatQuest:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\Nightfall")
GQ.BETASTART()
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\The War Within Pathfinder")
GQ.BETAEND()
GoatQuest:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\Siren Isle\\The Drain")
GoatQuest:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\Siren Isle\\The Drowned Lair")
GoatQuest:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\Siren Isle\\Shuddering Hollow")
GoatQuest:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\21st Anniversary Celebration\\21st Anniversary Event Weeklies")
GoatQuest:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\21st Anniversary Celebration\\Guest Relations")
GoatQuest:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\21st Anniversary Celebration\\Achievements\\No Crate Left Behind")
GoatQuest:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\21st Anniversary Celebration\\Achievements\\I Saved the Party and All I got Were These Lousy Hats")
GoatQuest:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\21st Anniversary Celebration\\Achievements\\Assistant to the Assistant Guest Relations Manager")
GoatQuest:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\21st Anniversary Celebration\\Achievements\\Peanut Gallery")
GoatQuest:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\21st Anniversary Celebration\\Achievements\\Pet Mischief")
GoatQuest:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\21st Anniversary Celebration\\Achievements\\Balloonist")
GoatQuest:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\21st Anniversary Celebration\\Achievements\\An Original")
GoatQuest:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\21st Anniversary Celebration\\Achievements\\Codex Editor: Ahn'Qiraj")
GoatQuest:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\21st Anniversary Celebration\\Achievements\\Classy Dresser")
GoatQuest:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\21st Anniversary Celebration\\Achievements\\Frequent Flyer")
GoatQuest:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\21st Anniversary Celebration\\Achievements\\Mount Master")
GoatQuest:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\21st Anniversary Celebration\\Achievements\\Azeroth's Greatest Detective")
GoatQuest:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\21st Anniversary Celebration\\Achievements\\Fashion Critic")
GoatQuest:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\21st Anniversary Celebration\\Achievements\\Big Fan")
GoatQuest:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\21st Anniversary Celebration\\Achievements\\Avid Listener")
GoatQuest:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\21st Anniversary Celebration\\Achievements\\Photo Op!")
GoatQuest:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\21st Anniversary Celebration\\Achievements\\The Gatecrashers")
GoatQuest:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\21st Anniversary Celebration\\Achievements\\Zoomies!")
GoatQuest:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\21st Anniversary Celebration\\Achievements\\The Originals")
GoatQuest:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\21st Anniversary Celebration\\Achievements\\I Have That One!")
GoatQuest:RegisterGuidePlaceholder("Events Guides\\The War Within (70-80)\\21st Anniversary Celebration\\Achievements\\A Gatecrasher")
