local GoatQuest=GoatQuest
if not GoatQuest then return end
if UnitFactionGroup("player")~="Horde" then return end
if GQ:DoMutex("GarrisonHWOD") then return end
GoatQuest.GuideMenuTier = "TRI"
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Buildings\\Small Buildings\\Alchemy Lab")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Buildings\\Small Buildings\\Enchanter's Study")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Buildings\\Small Buildings\\Engineering Works")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Buildings\\Small Buildings\\The Forge")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Buildings\\Small Buildings\\Gem Boutique")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Buildings\\Small Buildings\\Salvage Yard")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Buildings\\Small Buildings\\Scribe's Quarters")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Buildings\\Small Buildings\\Storehouse")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Buildings\\Small Buildings\\Tailoring Emporium")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Buildings\\Small Buildings\\The Tannery")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Buildings\\Medium Buildings\\Barn")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Buildings\\Medium Buildings\\Frostwall Tavern")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Buildings\\Medium Buildings\\Gladiator's Sanctum")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Buildings\\Medium Buildings\\Lumber Mill")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Buildings\\Medium Buildings\\Trading Post")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Buildings\\Large Buildings\\Barracks")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Buildings\\Large Buildings\\Goblin Workshop")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Buildings\\Large Buildings\\Spirit Lodge")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Buildings\\Large Buildings\\Stables")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Buildings\\Large Buildings\\War Mill")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Buildings\\Default Buildings\\Fishing Shack")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Buildings\\Default Buildings\\Frostwall Mines")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Buildings\\Default Buildings\\Herb Garden")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Buildings\\Default Buildings\\Menagerie")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Buildings\\Default Buildings\\Frostwall Shipyard")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Campaign Guide")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Tanaan Jungle (6.20) Garrison Campaign\\Onslaught at Auchindoun")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Tanaan Jungle (6.20) Garrison Campaign\\The Bane of the Bleeding Hollow")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Tanaan Jungle (6.20) Garrison Campaign\\In the Shadows")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Tanaan Jungle (6.20) Garrison Campaign\\The Warlock")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Leveling Guide")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Quests Guide")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Starter Guide")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower 'Doc' Schweitzer")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Abu'gar")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Aeda Brightdawn")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Ahm")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Aila Dourblade")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Aknor Steelbringer")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Alexi Barov")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Arienne Black")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Auriel Brightsong")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Awarri Blazecall")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Benjamin Gibb")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Bim'ini")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Blook")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Bruto")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Cacklebone")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Cadi Grasshoof")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Candice Morey")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Cheri")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Choluna")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Clever Ashyo")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Coggeye Aimbot")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Croman")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Cyril Fogus")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Dagg")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Dark Ranger Velonara")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Dawn Mercurus")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Dawnseeker Rukaryx")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Deneezo Hailstrike")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Eula Clay")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Faala")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Fazerra")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Fen Tao")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Fo Sho Knucklebump")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Glaiveweaver Xuan")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Goldmane the Skinner")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Gravewalker Gie")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Greatmother Geyah")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Gronnstalker Rokash")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Hannya")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Haomi")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Image of Archmage Vargoth")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Iye")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Ja'kala")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Ka'la")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Kaiel")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Kal'gor the Honorable")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Kaluaka")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Kana'tin")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Karg Bloodfury")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Karga Quickshot")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Karn Steelhoof")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Kaz the Shrieker")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Kil'weh")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Kimzee Pinchwhistle")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Lantresor of the Blade")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Leeroy Jenkins")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Leorajh")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Lin Tenderpaw")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Lokra")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Lonan")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Lucy Keller")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Magister Krelas")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Maska")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Matoclaw")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Mau'iti")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Meatball")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Millhouse Manastorm")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Morketh Bladehowl")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Motina")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Muaha Stonehide")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Mulverick")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Nat Pagle")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Nuan Skydream")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Olin Umberhide")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Penny Clobberbottom")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Phaedra Heartbinder")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Phylarch the Evergreen")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Pikake")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Pleasure-Bot 8000")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Professor Felblast")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Rizei Stormhoof")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Robin Fredericksen")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Ruthia the Unchaste")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Sahale")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Seleria Dawncaller")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Shadow Hunter Rala")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Skalliz Skullslice")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Soulare of Andorhal")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Soulbinder Tuulani")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Spirit of Bony Xuk")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Su-Lai Snowpetal")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Taela Shatterborne")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Tak'moa")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Talon Guard Kurekk")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Talonpriest Ishaal")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Tama Skyhoof")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Toega")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Tormmok")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Torwa Rimeheart")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Ulna Thresher")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Unkala Stormgrinder")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Utona Wolfeye")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Vella A'nar")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Vivianne")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Vol'motu")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Walsh Atkins")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Weaponsmith Na'Shra")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Xen Barleystrike")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Yu'un Tigersbite")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Zen'taki")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Zen'tenbi")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Zen'tiki")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Ziri'ak")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Scouting Missives")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Jukebox")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Mystery Notebook Questline")
