local GoatQuest=GoatQuest
if not GoatQuest then return end
if UnitFactionGroup("player")~="Alliance" then return end
if GQ:DoMutex("GarrisonAWOD") then return end
GoatQuest.GuideMenuTier = "TRI"
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Leveling Guide")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Buildings\\Small Buildings\\Alchemy Lab")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Buildings\\Small Buildings\\Enchanter's Study")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Buildings\\Small Buildings\\Engineering Works")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Buildings\\Small Buildings\\The Forge")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Buildings\\Small Buildings\\Gem Boutique")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Buildings\\Small Buildings\\Salvage Yard")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Buildings\\Small Buildings\\Scribe's Quarters")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Buildings\\Small Buildings\\Storehouse")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Buildings\\Small Buildings\\Tailoring Emporium")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Buildings\\Small Buildings\\The Tannery")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Buildings\\Medium Buildings\\Barn")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Buildings\\Medium Buildings\\Lunarfall Inn")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Buildings\\Medium Buildings\\Gladiator's Sanctum")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Buildings\\Medium Buildings\\Lumber Mill")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Buildings\\Medium Buildings\\Trading Post")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Buildings\\Large Buildings\\Barracks")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Buildings\\Large Buildings\\Gnomish Gearworks")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Buildings\\Large Buildings\\Mage Tower")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Buildings\\Large Buildings\\Stables")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Buildings\\Large Buildings\\Dwarven Bunker")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Buildings\\Default Buildings\\Fishing Shack")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Buildings\\Default Buildings\\Lunarfall Excavation")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Buildings\\Default Buildings\\Herb Garden")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Buildings\\Default Buildings\\Menagerie")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Buildings\\Default Buildings\\Lunarfall Shipyard")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Quest Guide")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Starter Guide")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Abu'gar")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Admiral Taylor")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Ahm")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Aknor Steelbringer")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Apprentice Artificer Andren")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Artificer Romuul")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Blook")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Bruma Swiftstone")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Cleric Maluuf")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Croman")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Dagg")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Daleera Moonfang")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Dawnseeker Rukaryx")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Defender Illona")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Delvar Ironfist")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Fen Tao")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Fiona")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Glirin")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Goldmane the Skinner")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Hulda Shadowblade")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Image of Archmage Vargoth")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Kimzee Pinchwhistle")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Lantresor of the Blade")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Leeroy Jenkins")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Leorajh")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Magister Serena")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Meatball")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Miall")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Millhouse Manastorm")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Nat Pagle")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Phylarch the Evergreen")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Pitfighter Vaandaam")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Pleasure-Bot 8000")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Professor Felblast")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Qiana Moonshadow")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Rangari Chel")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Rangari Erdanii")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Rangari Kaalya")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Rulkan")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Shelly Hamby")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Soulbinder Tuulani")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Talon Guard Kurekk")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Talonpriest Ishaal")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Thisalee Crow")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Tormmok")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Vindicator Onaala")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Weldon Barov")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Followers\\Follower Ziri'ak")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Campaign")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Tanaan Jungle (6.20) Garrison Campaign\\Onslaught at Auchindoun")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Tanaan Jungle (6.20) Garrison Campaign\\The Bane of the Bleeding Hollow")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Tanaan Jungle (6.20) Garrison Campaign\\In the Shadows")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Tanaan Jungle (6.20) Garrison Campaign\\The Warlock")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Inn Quest Guide")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Scouting Missives")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Garrison Jukebox")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Draenor (10-70)\\Garrisons\\Mystery Notebook Questline")
