local GoatQuest=GoatQuest
if not GoatQuest then return end
if GQ:DoMutex("LevelingCLEGION") then return end
GoatQuest.GuideMenuTier = "TRI"
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Legion Intro")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Azsuna")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Highmountain")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Stormheim")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Suramar")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Val'sharah")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Death Knight\\Death Knight Intro & Artifacts")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Death Knight\\Death Knight Order Hall Quests")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Demon Hunter\\Demon Hunter Intro & Artifacts")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Demon Hunter\\Demon Hunter Order Hall Quests")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Druid\\Druid Intro & Artifacts")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Druid\\Druid Order Hall Quests")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Evoker\\Evoker Intro")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Hunter\\Hunter Intro & Artifacts")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Hunter\\Hunter Order Hall Quests")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Mage\\Mage Intro & Artifacts")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Mage\\Mage Order Hall Quests")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Monk\\Monk Intro & Artifacts")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Monk\\Monk Order Hall Quests")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Paladin\\Paladin Intro & Artifacts")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Paladin\\Paladin Order Hall Quests")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Priest\\Priest Intro & Artifacts")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Priest\\Priest Order Hall Quests")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Rogue\\Rogue Intro & Artifacts")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Rogue\\Rogue Order Hall Quests")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Shaman\\Shaman Intro & Artifacts")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Shaman\\Shaman Order Hall Quests")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Warlock\\Warlock Intro & Artifacts")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Warlock\\Warlock Order Hall Quests")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Warrior\\Warrior Intro & Artifacts")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Warrior\\Warrior Order Hall Quests")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Legion Invasions")
GoatQuest:RegisterGuidePlaceholder("Dungeon Guides\\Legion Scenarios\\Argus Invasions")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Broken Shore Campaign")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\Argus Campaign")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Legion (10-70)\\The Hunt For Illidan Stormrage")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Legion Remix\\Legion Remix Campaign")
