local GoatQuest=GoatQuest
if not GoatQuest then return end
if UnitFactionGroup("player")~="Alliance" then return end
if GQ:DoMutex("LevelingABFA") then return end
GoatQuest.GuideMenuTier = "TRI"
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Tiragarde Sound (10-70)")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Drustvar (10-70)")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Stormsong Valley (10-70)")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Mechagon Island")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Nazjatar\\Nazjatar")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Nazjatar\\Nazjatar Dropped Quests")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\War Campaign")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Warfronts\\Arathi Highlands Warfront Extra Quests")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Warfronts\\Darkshore Warfront Extra Quests")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Warfronts\\Warfronts Introduction Quests")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Advanced Adventurer Augment")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Annoy-o-Tron Gang")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Anti-Gravity Pack")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Battle Box")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: BAWLD-371")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Beastbot Powerpack")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Blue Spraybot")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Canned Minnows")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Emergency Powerpack")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Emergency Repair Kit")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Emergency Rocket Chicken")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Encrypted Black Market Radio")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Experimental Adventurer Augment")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Extraordinary Adventurer Augment")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: G99.99 Landshark")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Green Spraybot")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Holographic Digitalization Relay")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Hundred-Fathom Lure")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Mechano-Treat")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Mechanocat Laser Pointer")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Microbot XD")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Orange Spraybot")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Perfectly Timed Differential")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Personal Time Displacer")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Protocol Transference Device")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Re-Procedurally Generated Punchcard")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Rustbolt Gramophone")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Rustbolt Kegerator")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Rustbolt Pocket Turret")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Rustbolt Resistance Insignia")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Rustbolt Requisitions")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Scrap Grenade")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Scrap Trap")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Scrapmaster's Blowtorch")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: S.P.A.R.E. Crate")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Ultrasafe Transporter - Mechagon")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Utility Mechanoclaw")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Mechagon Island\\Blueprints\\Blueprint: Vaultbot Key")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Scouting Reports\\Veiled Grotto (Zuldazar)")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Scouting Reports\\Grimwatt's Crash (Nazmir)")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Scouting Reports\\Mistvine Ledge (Zuldazar)")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Scouting Reports\\Mugamba Overlook (Zuldazar)")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Scouting Reports\\Verdant Hollow (Zuldazar)")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Scouting Reports\\Vulture's Nest (Vol'dun)")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Drustvar Loremaster (Story Quest Only)")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Stormsong Valley Loremaster (Story Quest Only)")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Kul Tiras\\Tiragarde Sound Loremaster (Story Quest Only)")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Mysterious Letter Questline")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Xal'atath's Gambit")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Xal'atath's Gambit - Priest")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Hati's Sacrifice")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Before the Storm Questline")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Heart of Azeroth\\Essential Empowerment")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Horrific Vision of Stormwind")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Horrific Vision of Orgrimmar")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Battle for Azeroth (10-70)\\Heart of Azeroth\\Magni's Plan")
