local GoatQuest=GoatQuest
if not GoatQuest then return end
if GQ:DoMutex("LevelingCMID") then return end
GoatQuest.GuideMenuTier = "TRI"
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Story Campaigns\\Midnight Intro & Campaign (Story Only)")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Story Campaigns\\Eversong Woods (Story Only)")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Story Campaigns\\Zul'Aman (Story Only)")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Story Campaigns\\Harandar (Story Only)")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Story Campaigns\\Arator's Journey (Story Only)")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Story Campaigns\\Voidstorm (Story Only)")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Full Zones (Story + Side Quests)\\Midnight Intro & Campaign (Full Zone)")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Full Zones (Story + Side Quests)\\Eversong Woods (Full Zone)")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Full Zones (Story + Side Quests)\\Zul'Aman (Full Zone)")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Full Zones (Story + Side Quests)\\Harandar (Full Zone)")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Full Zones (Story + Side Quests)\\Arator's Journey (Full Zone)")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Full Zones (Story + Side Quests)\\Voidstorm (Full Zone)")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Extra Storylines\\Delves: Season 2")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Extra Storylines\\Prey: Season 2")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Extra Storylines\\Abundance")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Extra Storylines\\Nulling Nullaeus")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Extra Storylines\\Pet Wranglin'")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Extra Storylines\\The Crimson Rogue")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Extra Storylines\\The Great Vault")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Extra Storylines\\Saltheril's Soiree")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Extra Storylines\\Ritual Site and Void Incursion Quest Guide")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Extra Storylines\\The Catalyst: Season 2")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Extra Storylines\\Legends of Haranir")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Extra Storylines\\Assault and Strike Back (Val)")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Extra Storylines\\Assault and Strike Back (Naigtal)")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Extra Storylines\\The Sunstrider Omnium")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Extra Storylines\\Lorewalking")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\The War of Light and Shadow Campaign")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Extra Storylines\\The Curse of Ula'tek Campaign")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Full Zones (Story + Side Quests)\\The Coiled Isle/Ula'tek Campaign")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\Extra Storylines\\Item Upgrade Tutorial: Season 2")
