local GoatQuest=GoatQuest
if not GoatQuest then return end
if GQ:DoMutex("LevelingCTWW") then return end
GoatQuest.GuideMenuTier = "TRI"
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Starter Guides\\Earthen Starter (10-11)")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Allied Races\\Earthen Race Unlock")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Allied Races\\Earthen Exploration Leveling (10-71)")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\The War Within (70-80)\\Story Campaigns\\Intro & Isle of Dorn (Story Only)")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\The War Within (70-80)\\Story Campaigns\\The Ringing Deeps (Story Only)")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\The War Within (70-80)\\Story Campaigns\\Hallowfall (Story Only)")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\The War Within (70-80)\\Story Campaigns\\Azj-Kahet (Story Only)")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\The War Within (70-80)\\Full Zones (Story + Side Quests)\\Intro & Isle of Dorn (Full Zone)")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\The War Within (70-80)\\Full Zones (Story + Side Quests)\\The Ringing Deeps (Full Zone)")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\The War Within (70-80)\\Full Zones (Story + Side Quests)\\Hallowfall (Full Zone)")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\The War Within (70-80)\\Full Zones (Story + Side Quests)\\Azj-Kahet (Full Zone)")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\The War Within (70-80)\\Story Campaigns\\The War Within Campaign")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\The War Within (70-80)\\Story Campaigns\\To Kill A Queen")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\The War Within (70-80)\\Skyriding Glyphs\\The War Within Skyriding Glyphs (All Zones)")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\The War Within (70-80)\\Full Zones (Story + Side Quests)\\Siren Isle")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\The War Within (70-80)\\Story Campaigns\\Lingering Shadows")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\The War Within (70-80)\\Story Campaigns\\The Fate of the Kirin Tor")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Prismatic Snapdragon")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\The War Within (70-80)\\Story Campaigns\\Undermine (Story Only)")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\The War Within (70-80)\\Full Zones (Story + Side Quests)\\Undermine (Full Zone)")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\The War Within (70-80)\\Story Campaigns\\Rise of the Red Dawn")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\The War Within (70-80)\\Story Campaigns\\K'aresh (Story Only)")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\The War Within (70-80)\\Full Zones (Story + Side Quests)\\K'aresh (Full Zone)")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\The War Within (70-80)\\Ecological Succession")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\The War Within (70-80)\\Visions of a Shadowed Sun")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\The War Within (70-80)\\Lorewalking Recap")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\The War Within (70-80)\\Catch Up")
GoatQuest:RegisterGuidePlaceholder("Leveling Guides\\Midnight (80-90)\\The Cult Within")
