local GoatQuest=GoatQuest
if not GoatQuest then return end
if GQ:DoMutex("AchievementsCMID") then return end
GoatQuest.GuideMenuTier = "TRI"
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Collect\\Midnight Safari")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Expansion Features\\Skyriding\\Eversong Woods Glyph Hunter")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Expansion Features\\Skyriding\\Harandar Glyph Hunter")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Expansion Features\\Skyriding\\Midnight Glyph Hunter")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Expansion Features\\Skyriding\\Voidstorm Glyph Hunter")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Expansion Features\\Skyriding\\Zul'Aman Glyph Hunter")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Midnight\\A Bloody Song")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Midnight\\Eversong Woods: The Highest Peaks")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Midnight\\Harandar: The Highest Peaks")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Midnight\\Midnight Lore Hunter")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Midnight\\Tallest Tree in the Forest")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Midnight\\Treasures of Eversong Woods")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Midnight\\Treasures of Harandar")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Midnight\\Treasures of Voidstorm")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Midnight\\Treasures of Zul'aman")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Midnight\\Voidstorm: The Highest Peaks")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Midnight\\Zul'Aman: The Highest Peaks")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Old World Family Battler")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Classic (1-60)\\Family Battler of Outland")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Classic (1-60)\\Aquatic Battler of Outland")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Classic (1-60)\\Beast Battler of Outland")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Classic (1-60)\\Critter Battler of Outland")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Classic (1-60)\\Dragonkin Battler of Outland")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Classic (1-60)\\Elemental Battler of Outland")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Classic (1-60)\\Flying Battler of Outland")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Classic (1-60)\\Humanoid Battler of Outland")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Classic (1-60)\\Magic Battler of Outland")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Classic (1-60)\\Mechanical Battler of Outland")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Classic (1-60)\\Undead Battler of Outland")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Classic (1-60)\\Family Battler of Cataclysm")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Classic (1-60)\\Aquatic Battler of Cataclysm")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Classic (1-60)\\Beast Battler of Cataclysm")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Classic (1-60)\\Critter Battler of Cataclysm")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Classic (1-60)\\Dragonkin Battler of Cataclysm")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Classic (1-60)\\Elemental Battler of Cataclysm")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Classic (1-60)\\Flying Battler of Cataclysm")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Classic (1-60)\\Humanoid Battler of Cataclysm")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Classic (1-60)\\Magic Battler of Cataclysm")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Classic (1-60)\\Mechanical Battler of Cataclysm")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Classic (1-60)\\Undead Battler of Cataclysm")
