local GoatQuest=GoatQuest
if not GoatQuest then return end
if UnitFactionGroup("player")~="Horde" then return end
if GQ:DoMutex("AchievementsHLEGION") then return end
GoatQuest.GuideMenuTier = "TRI"
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Class Hall\\Legion\\A Classy Outfit")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Class Hall\\Legion\\A Glorious Campaign")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Class Hall\\Legion\\Arsenal of Power")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Class Hall\\Legion\\Broken Isles Pathfinder, Part One")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\The Original")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\No Mercy")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\With a Vengeance")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Tough Threads")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Lethal Looks")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\The Fierce and the Furious")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Relentlessly Good Looking")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Wrath of the Stich King")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Viciously Vintage")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Ruth(less) is More")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Cataclysmic Catwalk")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Why Male(volent) Models?")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Dressed to Oppress")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\It's Not Fashion Unless it Hurts")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Wear it With Pride")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Untamed Beauty")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Wild Style")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\War-Mog-ering")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\More Like Win-dictive")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Cruel Intentions")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Accessor-Eyes")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Azeroth's Next Top Model")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Black is the New Black")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Can I Get A Helya")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Dress in Lairs")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Extreme Makeover: Fel Edition")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Fashionista: Back")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Fashionista: Chest")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Fashionista: Feet")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Fashionista: Hand")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Fashionista: Head")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Fashionista: Legs")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Fashionista: Shirt")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Fashionista: Shoulder")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Fashionista: Tabard")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Fashionista: Waist")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Fashionista: Weapon & Off Hand")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Fashionista: Wrist")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Glamour of Twilight")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Hot Couture")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Make it W-orc W-orc")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Merely a Set")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Mogg-Saron")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Outlandish Style")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Retro Trend")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Sha of Fabulous")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Style of the Crusader")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\So Hot Right Now")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Suns Out, Thori'dals Out")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\That's So Last Mellenium")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Thunderwear")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Undying Aesthetic")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Wardrobe of the Old Gods")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Winter Catalog")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Appearances\\Legion\\Yaass'shaarj")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Collections\\Legion\\The Tangerine Traveler")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\A Specter, Illuminated")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Adds? More Like Bads")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Arcanic Cling")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Black Rook Moan")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Burning Down the House")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\But you Say He's Just a Friend")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Can't Eat Just One")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Clean House")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Dropping Some Eaves")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Egg-cellent!")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Got to Ketchum All")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Helheim Hath No Fury")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\I Got What You Mead")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\I Made a Food!")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Instant Karma")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\No Time to Waste")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Poor Unfortunate Souls")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Ready for Raiding V")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Stag Party")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Stay Salty")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Surge Protector")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Waiting for Gerdo")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Who's Afraid of the Dark?")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\You Used to Scrawl Me In Your Fel Tome")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\You're Just Making It WORSE!")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\A Change In Scenery")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Bingo!")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Buggy Fight")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Burning Bridges")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Cage Rematch")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\The Chosen")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Dark Souls")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Elementalry!")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Fel Turkey!")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Five Course Seafood Buffet")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Fruit of All Evil")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Gluten Free")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Grand Fin-ale")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Grand Opening")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Great Soul, Great Purpose")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Grin and Bear it!")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\I Attack the Darkness")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\I've Got My Eyes On You")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Imagined Dragons World Tour")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Infinitesimal")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Gul'dan")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Xavius")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Don't Sweat the Technique")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Hard to Kill")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Hounds Good To Me")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Argus the Unmaker")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Portal Combat")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Remember the Titans")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Seat of the Pantheon")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Spheres of Influence")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Stardust Crusaders")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\This is the War Room!")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Together We Stand")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\The World Revolves Around Me")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Worm-monger")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Glory of the Argus Raider")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Not For You")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Scare Bear")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Sky Walker")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Took the Red Eye Down")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Unleashed Monstrosities")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Use the Force(s)")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Wax on, Wax off")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Webbing Crashers")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Glory of the Legion Hero")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\...And Chew Mana Buns")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Adventurer of Argus")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Broken Isles Explorer")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Broken Isles Pathfinder, Part Two")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Commander of Argus")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Envision Invasion Eradication")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Explore Argus")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Explore Azsuna")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Explore Broken Shore")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Explore Highmountain")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Explore Stormheim")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Explore Suramar")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Explore Val'sharah")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Higher Dimensional Learning")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Invasion Obliteration")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\To Kill Demons...")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Paragon of Argus")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Shoot First, Loot Later")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Universal Explorer")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Underbelly Tycoon")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\We Came Here For Two Reasons")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\And We're All Out of Mana Buns")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Feats of Strength\\Promotions\\Collector's Edition: Gilded Ravasaur")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Feats of Strength\\Promotions\\Collector's Edition: Tottle")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Aquatic Acquiescence")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Aquatic Assault")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Aquatic Brawler")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Beast Blitz")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Beast Brawler")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Best of the Beasts")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Critical Critters")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Critter Brawler")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Draconic Destruction")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Dragonkin Brawler")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Dragons!")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Elemental Brawler")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Elemental Escalation")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Family Brawler")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Family Familiar")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Family Fighter")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Fierce Fliers")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Flock Together")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Flying Brawler")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Humanoid Brawler")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Humanoid Havoc")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\The Lil'Necromancer")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Magic Brawler")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Magical Mayhem")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Master of Magic")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Mechanical Brawler")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Mechanical Melee")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Mousing Around")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Murlocs, Harpies, and Wolvar, Oh My!")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Ragnaros, Watch and Learn")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Roboteer")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\General\\Taming the Wild")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\General\\Taming the Great Outdoors")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\General\\Taming the World")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Undead Brawler")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Unstoppable Undead")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Collect\\Legion\\Raiding with Leashes V: Cuteaclysm")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Legion\\Pet Battle Challenge: Deadmines")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Legion\\Pet Battle Challenge: Wailing Caverns")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Collect\\Legion\\Broken Isles Safari")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\Crest of Heroism")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\Crest of Carnage")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\Crest of Devastation")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\Top Honors")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\First Step into a Larger World")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\Here We Go Again")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\Third Time's the Charm")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\For Prestige")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\Alive for Five")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\The River Six")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\Slayin' to Seven")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\Don't Hate. Grind to Eight")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\Hell. It's About Nine")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\Decade of Dominance")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\These Go To Elevan")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\Demonic Dozen")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\Floor Thirteen")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\Fourteen For The Team")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\When You're Fifteen")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\You Are Sixteen")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\Going On Seventeen")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\Eighteen and Over")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\Hell. It's About Nineteen")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\Double Decade of Dominance")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\Twenty-One Arms Salute")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\Catching Twenty-Two")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\Protocol 2.30")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\Demonic Double Dozen")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Honor\\Legion\\Prestige Quartermaster")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Legion\\Demonic Elite")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Legion\\Demonic Combatant")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Seething Shore\\A Good Start")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Seething Shore\\Blood and Sand")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Seething Shore\\Claim Jumper")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Seething Shore\\Death from Above")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Seething Shore\\Master of Seething Shore")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Seething Shore\\Seething Shore Domination")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Seething Shore\\Seething Shore Perfection")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Seething Shore\\Seething Shore Veteran")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Player vs. Player\\Seething Shore\\Seething Shore Victory")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Archaeology\\A Keen Eye")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Archaeology\\The Dwarven Dream")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Archaeology\\Getting Your Hands Dirty")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Archaeology\\Handle With Care")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Archaeology\\Legion Archaeologist")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Archaeology\\Legion Curator")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Archaeology\\No Stone Unturned")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Archaeology\\This Side Up")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Archaeology\\Sifting Through the Sand")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Archaeology\\Surveying the Land")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Cooking\\Everything Tastes Better")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Cooking\\Legion Cooking")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Cooking\\The Legion Menu")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Fishing\\A Cast Above the Rest")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Fishing\\Bigger Fish to Fry")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Fishing\\Fisherfriend of the Isles")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Fishing\\Fishing 'Round the Isles")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Fishing\\Legion Aquaculture")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Fishing\\Legion Fisherman")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Fishing\\The Wish Remover")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Hot Swapper")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Professions\\The Shortest Distance")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\50 World Quests Completed")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\200 World Quests Completed")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\500 World Quests Completed")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\1000 World Quests Completed")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\2500 World Quests Completed")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\5000 World Quests Completed")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\10,000 World Quests Completed")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\A Magic Contribution")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\A Magnificent Contribution")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Ain't No Mountain High Enough")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Assume Command")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Azsuna Matata")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Breaching the Tomb")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Champions of Legionfall")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Crate Expectations")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Defender of the Broken Isles")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Disrupting the Nether")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Good Suramaritan")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Harbinger")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Hatchling of the Talon")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Insurrection")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\It'll Nether Happen")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Leyline Bling")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Lock, Stock and Two Smoking Goblins")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Locked and Loaded")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Loremaster of Legion")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Nightfallen But Not Forgotten")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\No Shellfish Endeavor")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Now You're Thinking With Portals")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Pillars of Creation")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Post Haste")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Priority Mail")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Take Command")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Tehd & Marius' Excellent Adventure")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\That's Val'sharah Folks!")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\They See Me Rolling")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\The Total Package")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Variety is the Spice of Life")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Vrykul Story, Bro")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\What a Ripoff!")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Why Can't I Hold All This Mana?")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\You Are Now Prepared!")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\Legion\\Zoom!")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Reputation\\Legion\\Armies of Legionfall")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Reputation\\Legion\\Broken Isles Diplomat")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Reputation\\Legion\\Friends in a Broken Land")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Reputation\\Legion\\The Nightfallen")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Reputation\\Legion\\Officer of the Light")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Reputation\\Legion\\Paragon of the Broken Isles")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Reputation\\Legion\\Protector of the Argussian Reach")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Reputation\\Legion\\The Reputable")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\World Events\\Legion Brawler's Guild\\Educated Guesser")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\World Events\\Legion Brawler's Guild\\I Am Thrall's Complete Lack Of Surprise")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\World Events\\Legion Brawler's Guild\\King of the Guild")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\World Events\\Legion Brawler's Guild\\Rumble Club")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\World Events\\Legion Brawler's Guild\\You Are Not The Contents Of Your Wallet")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\World Events\\Darkmoon Faire\\Hey, You're a Rockstar!")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\World Events\\Darkmoon Faire\\Mosh Pit")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\World Events\\Darkmoon Faire\\Perfect Performance")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\World Events\\Darkmoon Faire\\Taking this Show on the Road")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Class Hall\\Legion\\A Heroic Campaign")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Class Hall\\Legion\\An Epic Campaign")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Class Hall\\Legion\\Champions of Power")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Class Hall\\Legion\\Champions Rise")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Class Hall\\Legion\\Fighting with Style: Classic")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Class Hall\\Legion\\Forged for Battle")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Class Hall\\Legion\\Improving on History")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Class Hall\\Legion\\Lead a Legion")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Class Hall\\Legion\\Legendary Research")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Class Hall\\Legion\\Many Many Missions, Handle It!")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Class Hall\\Legion\\Many Missions")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Class Hall\\Legion\\Need Backup")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Class Hall\\Legion\\Quite a Few Missions")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Class Hall\\Legion\\Raise an Army")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Class Hall\\Legion\\Roster of Champions")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Class Hall\\Legion\\So Many Missions")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Class Hall\\Legion\\There's a Boss In There")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Class Hall\\Legion\\Training the Troops")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\A Steamy Romance Saga")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Boom Bloom")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Broken Isles Keymaster")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Burn After Reading")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Darker Side")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Dine and Bash")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Heroic: Assault on Violet Hold")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Heroic: Black Rook Hold")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Heroic: Darkheart Thicket")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Heroic: Eye of Azshara")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Heroic: Halls of Valor")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Heroic: Neltharion's Lair")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Heroic: Maw of Souls")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Heroic: Return to Karazhan")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Heroic: Seat of the Triumvirate")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Heroic: Vault of the Wardens")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Keystone Challenger")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Keystone Conqueror")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Keystone Initiate")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Keystone Master")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Let it All Out")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Master of Shadows")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Mythic: Assault on Violet Hold")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Mythic: Black Rook Hold")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Mythic: Cathedral of Eternal Night")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Mythic: Darkheart Thicket")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Mythic: Eye of Azshara")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Mythic: Halls of Valor")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Mythic: Maw of Souls")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Mythic: Neltharion's Lair")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Mythic: Return to Karazhan")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Mythic: Seat of the Triumvirate")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Mythic: Vault of the Wardens")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\One Night in Karazhan")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\The Rat Pack")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Scared Straight")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Season Tickets")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Welcome the Void")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Arcing Aqueducts")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Betrayer's Rise")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Boneafide Tri Tip")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Chamber of the Avatar")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Darkbough")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Deceiver's Fall")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\The Gates of Hell")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Heroic: Trial of Valor")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Cenarius")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Chronomatic Anomaly")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Demonic Inquisition")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Desolate Host")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Dragons of Nightmare")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Elerethe Renferal")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Fallen Avatar")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Goroth")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Grand Magistrix Elisande")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Guarm")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Harjatan")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Helya")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: High Botanist Tel'arn")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Il'gynoth")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Kil'Jaeden")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Krosus")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Maiden of Vigilance")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Mistress Sassz'ine")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Nythendra")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Odyn")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Sisters of the Moon")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Skorpyron")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Spellblade Aluriel")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Star Augur Etraeus")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Tichondrius")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Trilliax")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Ursoc")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Forbidden Descent")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Hope's End")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Light's Breach")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Aggramar")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Antoran High Command")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: The Coven of Shivarra")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Eonar")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Garothi Worldbreaker")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Hounds of Sargeras")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Imonar the Soulhunter")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Kin'garoth")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Portal Keeper Hasabel")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Mythic: Varimathras")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Nightspire")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Patient Zero")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Rift of Aln")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Royal Athenaeum")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Terrors of the Shore")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Tormented Guardians")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Trial of Valor")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\Wailing Halls")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Raids\\You Ruined Everything!")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Legion Dungeons\\Legion Dungeon Hero")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Adventurer of Azsuna")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Adventurer of Highmountain")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Adventurer of Stormheim")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Adventurer of Suramar")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Adventurer of Val'sharah")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Bringing Home the Beacon")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Infused and Abused")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Going Up")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Naxt Victim")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Treasures of Azsuna")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Treasures of Highmountain")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Treasures of Stormheim")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Treasures of Suramar")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Legion\\Treasures of Val'sharah")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Feats of Strength\\Raids\\Legion\\Ahead of the Curve: Argus the Unmaker")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Feats of Strength\\Raids\\Legion\\Cutting Edge: Argus the Unmaker")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Feats of Strength\\Raids\\Cutting Edge: Gul'dan")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Legacy\\Expansion Features\\Artifact or Artifiction")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Legacy\\Expansion Features\\Crucible's Promise")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Legacy\\Expansion Features\\Now You're Cooking with Netherlight")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Legacy\\Expansion Features\\Part of History")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Legacy\\Expansion Features\\Power Ascended")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Legacy\\Expansion Features\\Power Realized")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Legacy\\Expansion Features\\Power Unbound")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Legacy\\Expansion Features\\Power Unleashed")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Legacy\\Professions\\Is There a Medic in the Zone?")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Legacy\\Chapter I: Call of the Archmage")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Legacy\\Chapter II: Gul'dan Strikes Back")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Legacy\\Chapter III: The Foundry Falls")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Legacy\\Chapter IV: Darkness Incarnate")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Pet Battles\\Battle\\Legion\\Anomalous Animals of Argus")
