local GoatQuest=GoatQuest
if not GoatQuest then return end
if GQ:DoMutex("AchievementsCBFA") then return end
GoatQuest.GuideMenuTier = "TRI"
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Battle Raid\\Battle of Dazar'alor")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Battle Raid\\The Eternal Palace")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Battle Raid\\The Grand Reception")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Battle Raid\\Depths of the Devoted")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Battle Raid\\The Circle of Stars")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Battle Raid\\Ny'alotha, the Waking City")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Battle Raid\\Vision of Destiny")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Battle Raid\\Halls of Devotion")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Battle For Azeroth\\Gift of Flesh")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Battle Raid\\The Waking Dream")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\I'm On Island Time")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\A Load of a Tale")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\Hot Tropic")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\Sound Off")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\Sailed in Sea Minor")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\Bwon Voyage")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\A Most Efficient Apocalypse")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\Songs of Storms")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\Dune Squad")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\When the Drust Settles")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\War Stories")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\Two Sides to Every Tale")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\The Corruptor's End")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\Maximum Effort")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\Frontline Warrior")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\Undersea Usurper")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\Mecha-Done")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\Junkyard Machinist")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\Black Empire State of Mind")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\The Rajani")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\Uldum Accord")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\Combating the Corruption")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\It's Not A Tumor!")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\All Consuming")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\Defend the Vale")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\Uldum Under Assault")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\Full Heart, Can't Lose")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\The Heart Forge")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\Power Is Beautiful")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\My Heart Container is Full")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\Dressed to Kill: Battle for Azeroth")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\Under the Seams")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\Never Lose, Never Choose To")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\All Eyes On Me")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\The Eyes Have It")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\Battle For Azeroth\\A Farewell to Arms")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Battle Raid\\Uldir")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Battle Raid\\Halls of Containment")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Battle Raid\\Crimson Descent")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Battle Raid\\Heart of Corruption")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\Battle Raid\\Battle of Dazar'alor")
