local GoatQuest=GoatQuest
if not GoatQuest then return end
if GQ:DoMutex("AchievementsCTWW") then return end
GoatQuest.GuideMenuTier = "TRI"
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Biblo Archivist")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\War Within\\Explore K'aresh")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Khaz Algar Glyph Hunter")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\K'aresh Glyph Hunter")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\The Missing Lynx")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Khaz Algar Safari")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Lost and Found")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\The War Within Achievements\\Secrets of the K'areshi")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within\\Exploration\\Treasures of K'aresh")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Feats of Strength\\Events\\Two Minutes to Midnight")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\TWW Raids\\Glory of the Nerub-ar Raider")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Quests\\Loremaster of Khaz Algar")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Quests\\The Isle of Dorn")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Quests\\The Ringing Deeps")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Quests\\Hallowfall")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Quests\\Azj-Kahet")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Quests\\Sojourner of Isle of Dorn")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Quests\\Sojourner of The Ringing Deeps")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Quests\\Sojourner of Hallowfall")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Quests\\Sojourner of Azj-Kahet")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\You Xal Not Pass")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Adventurer of the Isle of Dorn")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Treasures of the Isle of Dorn")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Flat Earthen")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\We're Here All Night")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\A Star of Dorn")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Rocked to Sleep")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Adventurer of The Ringing Deeps")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Treasures of The Ringing Deeps")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\It's Not Much, But It's Honest Work")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Notable Machines")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\To All the Slimes I Love")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Super Size Snuffling")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Not So Quick Fix")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Adventurer of Hallowfall")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Treasures of Hallowfall")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Mereldar Menace")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Beacon of Hope")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Igniting the Keyflames")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Sharing the Light")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Children's Entertainer")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Adventurer of Azj-Kahet")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Treasures of Azj-Kahet")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\You Can't Hang With Us")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\The Unseeming")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Worm Theory")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Itsy Bitsy Spider")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Smelling History")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Bookworm")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\A Song of Secrets")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Siren-ity Now!")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Excavation Projects")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Treasures of the Storm")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\A Choir of Citrines")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Slate of the Union")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Rage Aside the Machine")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Isle Remember You")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Crystal Chronicled")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Exploration\\Azj the World Turns")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\Leave No Treasure Unfound")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\The Dread Pit Discoveries")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\The Waterworkds Discoveries")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\Fungal Folly Discoveries")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\Kriegval's Rest Discoveries")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\Mycomancer Cavern Discoveries")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\Nightfall Sanctum Discoveries")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\Skittering Breach Discoveries")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\The Sinkhole Discoveries")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\Tak-Rethan Abyss Discoveries")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\The Spiral Weave Discoveries")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\Excavation Site 9 Discoveries")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\Sidestreet Sluice Discoveries")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\The Underkeep Discoveries")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\Earthcrawl Mines Discoveries")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Dungeons & Raids\\War Within Raids\\One Rank Higher")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Dungeons & Raids\\War Within Raids\\Two Ranks Higher")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Dungeons & Raids\\War Within Raids\\Three Ranks Higher")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Dungeons & Raids\\War Within Raids\\Best In Class")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Quests\\War Within\\Fate of the Kirin Tor")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\Delve Beyond")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\Delve Infinite")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\Delver's Dirigible Recovery")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Quests\\War Within\\Read Between the Lines")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Pet Battles\\War Within\\Family Battler of Undermine")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Pet Battles\\War Within\\Aquatic Battler of Undermine")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Pet Battles\\War Within\\Beast Battler of Undermine")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Pet Battles\\War Within\\Critter Battler of Undermine")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Pet Battles\\War Within\\Dragonkin Battler of Undermine")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Pet Battles\\War Within\\Elemental Battler of Undermine")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Pet Battles\\War Within\\Flying Battler of Undermine")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Pet Battles\\War Within\\Humanoid Battler of Undermine")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Pet Battles\\War Within\\Magic Battler of Undermine")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Pet Battles\\War Within\\Mechanical Battler of Undermine")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Pet Battles\\War Within\\Undead Battler of Undermine")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Raids\\A Good Day to Dye Hard")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\The Key to Madness")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Reputation\\War Within\\In with the Cartels")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\Glory of the Delver")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\Sporesweeper")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\Just Keep Swimming")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\Spider Senses")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\Daystormer")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\Brann Development")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\My First Nemesis")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Delves\\My New Nemesis")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Raids\\Glory of the Liberation of Undermine Raider")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Raids\\Garbage In, Garbage Out")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Raids\\Hold My Gear!")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Raids\\Just /Dance")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Raids\\The Splash Zone")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Raids\\Conveyor Slayer")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Raids\\Sleep with the Fishes")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Raids\\Scheming on a Thing")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Exploration\\War Within\\C.H.E.T.T.mate")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Raids\\Slimy Yet Satisfying")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Raids\\Sik Parry Bro")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Raids\\Would You Still /love Me if I Was a Worm...")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Raids\\Love is in the Lair")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Raids\\You Can't See Me")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Raids\\Cowabunga")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Raids\\Kill Streak")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Raids\\Missed 'Em by That Much")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Raids\\Allied Races: Earthen")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Quests\\War Within\\The Grand Tapestry")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Exploration\\War Within\\Grand, Gutsy Solutions")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Expansion Features\\Skyriding\\Undermine Breaknecking: Bronze")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Dungeons & Raids\\War Within Raids\\Algari Dungeoneer")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Algari Dungeon Damage Dealer")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Algari Dungeon Healer")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Algari Dungeon Tank")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Character Achievements\\Reputation\\The War Within Achievements\\Khaz Algar Diplomat")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\Sojourner of Undermine")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\The War Within Achievements\\Khaz Algar Lore Hunter")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\The War Within Achievements\\Going Goblin Mode")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\The War Within Achievements\\Adventurer of Undermine")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\The War Within Achievements\\Treasures of Undermine")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\The War Within Achievements\\Nine-Tenths of the Law")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Quests\\The War Within Achievements\\You're My Friend Now")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\The War Within Achievements\\That Can-Do Attitude")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\The War Within Achievements\\Undermined")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\The War Within Achievements\\C.H.E.T.T. a Look")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Exploration\\The War Within Achievements\\Gobblin' with Glublurp")
GoatQuest:RegisterGuidePlaceholder("Achievement Guides\\Dungeons & Raids\\The War Within Achievements\\Flarendo's Biggest Fan")
