local GoatQuest=GoatQuest
if not GoatQuest then return end
if GQ:DoMutex("PetsCMID") then return end
GoatQuest.GuideMenuTier = "TRI"
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Battle Pets\\Beast Pets\\Vendor Pets\\Cappy")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Battle Pets\\Beast Pets\\Ritual Site Pets\\Chubs")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Battle Pets\\Beast Pets\\Drop Pets\\Curious Lynx Kitten")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Battle Pets\\Beast Pets\\Achievement Pets\\Do, Child of Filo")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Battle Pets\\Beast Pets\\Gortham")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Battle Pets\\Beast Pets\\Princess Bloodshed")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Battle Pets\\Beast Pets\\Drop Pets\\Wriggling Capybara")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Battle Pets\\Dragonkin Pets\\Dragonhawk Munchkin")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Battle Pets\\Dragonkin Pets\\Achievement Pets\\Furiostraza")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Battle Pets\\Dragonkin Pets\\Ritual Site Pets\\Rescued Dragonhawk Chick")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Battle Pets\\Flying Pets\\Dropped Pets\\Void-Scarred Eaglet")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Battle Pets\\Humanoid Pets\\Achievement Pets\\Lil'Kruul")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Battle Pets\\Humanoid Pets\\Promotion Pets\\Murk'atath")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Battle Pets\\Magic Pets\\Vendor Pets\\Lil' Preyseeker")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Battle Pets\\Magic Pets\\Vendor Pets\\Void-Infused Mindbreaker Fry")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Battle Pets\\Mechanical Pets\\Vendor Pets\\Preyhunter's Prismguard")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Battle Pets\\Mechanical Pets\\Vendor Pets\\Preyhunter's Riftbreaker")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Quest Pets\\Akiki")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Akil Fledgling")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Amber Treeflitter")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Quest Pets\\Assistant Botanist Leafy")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Autumn Snapling")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Azure Sporebat")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Blistercreepling")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Profession Pets\\Bubbly Snapling")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Caustic Writhling")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Vendor Pets\\Corrosive Writhling")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Cursed Spawn")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Treasure Pets\\Dali")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Devouring Runt")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Dragonhawk Mosswing")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Ebon Snapling")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Emberwing Hatchling")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Emerald Hatchling")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Quest Pets\\Fidoficus")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Vendor Pets\\Flicker")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Gloom Toad")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Delve Pets\\Hexed Bunny")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Quest Pets\\Hawkstrider Hatchling")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Jaundiced Slitherer")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Vendor Pets\\Kreepah'zoyd")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Drop Pets\\Lil' Mon")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Quest Pets\\Linda the Lucky")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Delve Pets\\Lost Star")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Quest Pets\\Luma")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Mud Potadpole")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Vendor Pets\\Naloki")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Nether Familiar")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Treasure Pets\\Nether Siphoner")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Delve Pets\\Nibblesworth")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Achievement Pets\\Niblet")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Nightfur Kapara")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Delve Pets\\Ominous Domanus")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Pangolil")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Treasure Pets\\Percival")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Drop Pets\\Poison Dart Frog")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Poisoned Parasite")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Riftblade Familiar")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Rootling Nester")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Battle Pets\\Treasure Pets\\Scruffbeak")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Silkcrawler")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Silvermoon Broom")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Sleek Snakebiter")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Vendor Pets\\Snek'zali")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Achievement Pets\\Sootpaw")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Delve Pets\\Sporbie")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Delve Pets\\Spormilian")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Steady Croakfrog")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Striped Snakebiter")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Treasure Pets\\Sunwing Hatchling")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Swamp Biter")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Delve Pets\\Treja'saka")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Vibrant Manaling")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Violet Chick")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Voidcrawler")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Vendor Pets\\Volatile Venomfang")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Vendor Pets\\Voldy")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Aquatic Pets\\Zone Pets\\Waddles")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Treasure Pets\\Willie")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Zone Pets\\Wrathful Wyrm")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Quest Pets\\Zan")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Peaceful Pets\\Delve Pets\\Ziorg'pharon")
