local GoatQuest=GoatQuest
if not GoatQuest then return end
if UnitFactionGroup("player")~="Horde" then return end
if GQ:DoMutex("HunterPetHWOD") then return end
GoatQuest.GuideMenuTier = "TRI"
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Beast Mastery Exotic Pets\\Clefthooves\\Greater Clefthooves\\Blue Greater Clefthoof")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Beast Mastery Exotic Pets\\Clefthooves\\Greater Clefthooves\\Brown Greater Clefthoof")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Beast Mastery Exotic Pets\\Clefthooves\\Greater Clefthooves\\Grey Greater Clefthoof")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Beast Mastery Exotic Pets\\Clefthooves\\Greater Clefthooves\\Red Greater Clefthoof")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Beast Mastery Exotic Pets\\Clefthooves\\Greater Clefthooves\\White Greater Clefthoof")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Beast Mastery Exotic Pets\\Clefthooves\\Saddled Greater Clefthooves\\Brown Saddled Greater Clefthoof")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Beast Mastery Exotic Pets\\Clefthooves\\Saddled Greater Clefthooves\\Grey Saddled Greater Clefthoof")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Beast Mastery Exotic Pets\\Clefthooves\\Saddled Greater Clefthooves\\Red Saddled Greater Clefthoof")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Beast Mastery Exotic Pets\\Clefthooves\\Saddled Greater Clefthooves\\White Saddled Greater Clefthoof")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Beast Mastery Exotic Pets\\Clefthooves\\Brown and Fawn Clefthoof")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Beast Mastery Exotic Pets\\Clefthooves\\Brown Clefthoof")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Beast Mastery Exotic Pets\\Clefthooves\\Dark Brown Clefthoof")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Beast Mastery Exotic Pets\\Clefthooves\\Grey Clefthoof")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Beast Mastery Exotic Pets\\Clefthooves\\Red Clefthoof")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Beast Mastery Exotic Pets\\Clefthooves\\Red-Brown Clefthoof")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Beast Mastery Exotic Pets\\Rylaks\\Armored Rylaks\\Red Armored Rylak")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Beast Mastery Exotic Pets\\Rylaks\\Black Rylak")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Beast Mastery Exotic Pets\\Rylaks\\Green Rylak")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Beast Mastery Exotic Pets\\Rylaks\\Pale Rylak")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Beast Mastery Exotic Pets\\Rylaks\\Red Rylak")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Beast Mastery Exotic Pets\\Rylaks\\Silver Rylak")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Beast Mastery Exotic Pets\\Rylaks\\Yellow Rylak")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Beast Mastery Exotic Pets\\Spirit Beasts\\Spirit Wolves\\Shadowy Purple Spirit Wolf")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Beast Mastery Exotic Pets\\Worms\\Jormungars\\Red Jormungar")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Basilisks\\Crested Basilisks\\Red and Purple Crested Basilisk")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Boars\\Greater Boars\\Black Greater Boar")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Boars\\Greater Boars\\Brown Greater Boar")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Boars\\Greater Boars\\Fel Green Greater Boar")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Boars\\Greater Boars\\Grey-Brown Greater Boar")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Boars\\Greater Boars\\Red Greater Boar")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Boars\\Greater Boars\\Silver Greater Boar")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Boars\\Greater Boars\\White Greater Boar")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Cats\\Grand Tigers\\Black and Red Grand Tiger")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Cats\\Grand Tigers\\White and Red Grand Tiger")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Hydras\\Azeroth Hydras\\Black Azeroth Hydra")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Hydras\\Azeroth Hydras\\Blue Azeroth Hydra")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Hydras\\Azeroth Hydras\\Ghost Azeroth Hydra")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Hydras\\Azeroth Hydras\\Green Azeroth Hydra")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Hydras\\Azeroth Hydras\\Grey Azeroth Hydra")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Hydras\\Azeroth Hydras\\Purple Azeroth Hydra")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Hydras\\Azeroth Hydras\\Red Azeroth Hydra")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Hydras\\Azeroth Hydras\\White Azeroth Hydra")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Hydras\\Outland Hydras\\Blue Outland Hydra")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Hydras\\Outland Hydras\\Green Outland Hydra")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Hydras\\Outland Hydras\\Grey Outland Hydra")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Hydras\\Outland Hydras\\Orange Outland Hydra")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Hydras\\Outland Hydras\\Purple Outland Hydra")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Hydras\\Thunder Hydras\\Blue Thunder Hydra")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Hydras\\Thunder Hydras\\Green Thunder Hydra")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Hydras\\Thunder Hydras\\Purple Thunder Hydra")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Hydras\\Thunder Hydras\\Red Thunder Hydra")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Hydras\\Chimaeron")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Raptors\\Greater Raptors\\Blue Greater Raptor")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Raptors\\Greater Raptors\\Dark Green Greater Raptor")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Raptors\\Greater Raptors\\Green Greater Raptor")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Raptors\\Greater Raptors\\Red Greater Raptor")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Raptors\\Greater Raptors\\Yellow Greater Raptor")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Ravagers\\Winged Ravagers\\Black Winged Ravager")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Ravagers\\Winged Ravagers\\Blue Winged Ravager")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Ravagers\\Winged Ravagers\\Buff Winged Ravager")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Ravagers\\Winged Ravagers\\Green Winged Ravager")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Ravagers\\Winged Ravagers\\Icy Blue Winged Ravager")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Ravagers\\Winged Ravagers\\Red Winged Ravager")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Ravagers\\Winged Ravagers\\Yellow Winged Ravager")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Riverbeasts\\Blue Riverbeast")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Riverbeasts\\Dark Brown Riverbeast")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Riverbeasts\\Green Riverbeast")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Riverbeasts\\Pale Riverbeast")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Riverbeasts\\Red-Brown Riverbeast")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Stags\\Gazelles\\Black Gazelle")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Stags\\Gazelles\\Diseased Gazelle")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Stags\\Gazelles\\Striped Tan Gazelle")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Stags\\Gazelles\\Tan and Black Gazelle")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Stags\\Greater Stags\\Patterned Dark Brown Greater Stag")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Stags\\Greater Stags\\Patterned Green-Brown Greater Stag")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Stags\\Greater Stags\\Patterned Grey Greater Stag")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Stags\\Greater Stags\\Patterned Orange Greater Stag")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Stags\\Greater Stags\\Patterned White Greater Stag")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Stags\\Greater Talbuks\\Black Greater Talbuk")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Stags\\Greater Talbuks\\Purple Greater Talbuk")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Stags\\Greater Talbuks\\Red Greater Talbuk")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Stags\\Greater Talbuks\\Silver Greater Talbuk")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Stags\\Greater Talbuks\\Tan Greater Talbuk")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Stags\\Old World Stags\\Black Old World Stag")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Stags\\Old World Stags\\Brown Old World Stag")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Stags\\Old World Stags\\Silver Old World Stag")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Stags\\Talbuks\\Black Talbuk")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Stags\\Talbuks\\Brown Talbuk")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Stags\\Talbuks\\Indigo Talbuk")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Stags\\Talbuks\\Lavender Talbuk")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Stags\\Talbuks\\White Talbuk")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Stags\\Reindeer")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Warp Stalkers\\Black Warp Stalker")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Wolves\\Iron Horde Wolves\\Iron Horde Wolf")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Wolves\\Maned Wolves\\Black Maned Wolf")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Wolves\\Maned Wolves\\Brown Armored Maned Wolf")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Wolves\\Maned Wolves\\Brown Maned Wolf")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Wolves\\Maned Wolves\\Fel Green Maned Wolf")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Wolves\\Maned Wolves\\Grey Maned Wolf")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Wolves\\Maned Wolves\\Silver Maned Wolf")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Ground Pets\\Wolves\\Saddled Maned Wolves\\Saddled Brown Maned Wolf")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Flying Pets\\Bats\\Greater Bats\\Grey-Brown Greater Bat")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Flying Pets\\Bats\\Greater Bats\\Red-Black Greater Bat")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Flying Pets\\Bats\\Greater Bats\\Tan-Brown Greater Bat")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Flying Pets\\Bats\\Greater Bats\\White Greater Bat")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Flying Pets\\Birds of Prey\\Axebeaks\\Black Axebeak")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Flying Pets\\Birds of Prey\\Axebeaks\\Blue Axebeak")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Flying Pets\\Birds of Prey\\Axebeaks\\Green Axebeak")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Flying Pets\\Birds of Prey\\Axebeaks\\Red Axebeak")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Flying Pets\\Birds of Prey\\Draenor Kaliri\\Black Draenor Kaliri")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Flying Pets\\Birds of Prey\\Draenor Kaliri\\Brown Draenor Kaliri")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Flying Pets\\Birds of Prey\\Draenor Kaliri\\Red Draenor Kaliri")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Flying Pets\\Carrion Birds\\Teroclaws\\Blue-Black Teroclaw")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Flying Pets\\Carrion Birds\\Teroclaws\\Red-Brown Teroclaw")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Flying Pets\\Carrion Birds\\Teroclaws\\Yellow-Brown Teroclaw")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Flying Pets\\Carrion Birds\\Teroclaws\\Young Red Teroclaw")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Flying Pets\\Moths\\Cyan-Blue and White Moth")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Flying Pets\\Moths\\Indigo and White Moth")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Flying Pets\\Moths\\Pink Moth")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Flying Pets\\Moths\\Red and White Moth")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Flying Pets\\Moths\\White and Cyan Moth")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Flying Pets\\Sporebats\\Greater Sporebats\\Blue Greater Sporebat")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Flying Pets\\Sporebats\\Greater Sporebats\\Grey Greater Sporebat")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Flying Pets\\Sporebats\\Greater Sporebats\\Purple Greater Sporebat")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Flying Pets\\Wasps\\Dire Wasps\\Blue Dire Wasp")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Flying Pets\\Wasps\\Dire Wasps\\Buff Dire Wasp")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Flying Pets\\Wasps\\Dire Wasps\\Dark Green Dire Wasp")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Flying Pets\\Wasps\\Dire Wasps\\Green Dire Wasp")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Flying Pets\\Wasps\\Dire Wasps\\Red Dire Wasp")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Flying Pets\\Wasps\\Dire Wasps\\Yellow Dire Wasp")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Flying Pets\\Wasps\\Fireflies\\Aqua Firefly")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Flying Pets\\Wasps\\Fireflies\\Blue Firefly")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Flying Pets\\Wasps\\Fireflies\\Magenta Firefly")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Flying Pets\\Wasps\\Fireflies\\Orange Firefly")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Water Pets\\Crabs\\Spiked Crabs\\Blue-Tinged Dark Red Spiked Crab")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Water Pets\\Crabs\\Spiked Crabs\\Blue-Marked Deep Red Spiked Crab")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Water Pets\\Crabs\\Spiked Crabs\\Greenish-Blue Spiked Crab")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Water Pets\\Crabs\\Silver Crab")
