local GoatQuest=GoatQuest
if not GoatQuest then return end
if GQ:DoMutex("MountsCMID") then return end
GoatQuest.GuideMenuTier = "TRI"
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Trading Post Mounts\\Arboreal Pseudoshell")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Vendor Mounts\\Amani Blessed Bear")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Dropped Mounts\\Ancestral War Bear")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Vendor Mounts\\Blessed Amani Burrower")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Dropped Mounts\\Cerulean Hawkstrider")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Vendor Mounts\\Crimson Silvermoon Hawkstrider")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Quest Mounts\\Emerald Hawkstrider")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Vendor Mounts\\Fierce Grimlynx")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Vendor Mounts\\Frenzied Shredclaw")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Trading Post Mounts\\Gilneas Loyalist's Rouncey")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Dropped Mounts\\Insatiable Shredclaw")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Dropped Mounts\\Lucent Hawkstrider")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Vendor Mounts\\Prowling Shredclaw")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Trading Post Mounts\\Pyrewood Rebel's Rouncey")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Quest Mounts\\Relinquished Scarlet Charger")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Dropped Mounts\\Rootstalker Grimlynx")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Vendor Mounts\\Skypaw Glimmerfur")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Dropped Mounts\\Spectral Hawkstrider")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Dropped Mounts\\Untainted Grove Crawler")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Achievement Mounts\\Vivacious Chloroceros")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Profession Mounts\\Void-Corrupted Lynx")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Vendor Mounts\\Vivid Chloroceros")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Vendor Mounts\\Void-Touched Hawkstrider")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Dropped Mounts\\Witherbark Pango")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Dropped Mounts\\Witherbark Warbear Mother")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Dropped Mounts\\Amani Sharptalon")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Vendor Mounts\\Amani Sunfeather")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Vendor Mounts\\Amani Windcaller")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\In-Game Shop Mounts\\Amberback Arboon")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Achievement Mounts\\Arcanovoid Construct")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Dropped Mounts\\Ashes of Belo'ren")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Trading Post Mounts\\Blackwater X-TREME Firework Rocket")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\In-Game Shop Mounts\\Blossomback Arboon")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Achievement Mounts\\Calamitous Carrion")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Vendor Mounts\\Caustic Venomfang")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Vendor Mounts\\Cerulean Sporeglider")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Dropped Mounts\\Cobalt Dragonhawk")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Trading Post Mounts\\Comfy Bel'ameth Flying Quilt")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Trading Post Mounts\\Comfy Silvermoon Flying Quilt")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Achievement Mounts\\Convalescent Carrion")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Vendor Mounts\\Elven Arcane Guardian")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Vendor Mounts\\Fiery Dragonhawk")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Puzzle Mounts\\Luminous Sporeglider")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Quest Mounts\\Peridot Dragonhawk")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Dropped Mounts\\Ruddy Sporeglider")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Promotion Mounts\\Scorching Valor")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Achievement Mounts\\Tenebrous Harrower")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Vendor Mounts\\Unbound Manawyrm")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Dropped Mounts\\Vibrant Petalwing")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Trading Post Mounts\\Vicious Snapvine")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Dropped Mounts\\Void-Corrupted Hex Eagle")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Aquatic Mounts\\Trading Post Mounts\\Savage Crimson Battle Turtle")
