local GoatQuest=GoatQuest
if not GoatQuest then return end
if GQ:DoMutex("PetsMountsCTWW") then return end
GoatQuest.GuideMenuTier = "TRI"
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Achievement Mounts\\Coldflame Tempest")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Achievement Mounts\\Crimson Shreddertank")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Achievement Mounts\\Diamond Mechsuit")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Achievement Mounts\\Enterprising Shreddertank")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Achievement Mounts\\Ivory Goliathus")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Achievement Mounts\\Junkmaestro's Magnetomech")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Achievement Mounts\\Light-Forged Mechsuit")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Achievement Mounts\\Shadowed Swarmite")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Achievement Mounts\\Swarmite Skyhunter")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Blizzard Store Mounts\\Archmage's Great Raven")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\In-Game Shop Mounts\\Astral Aurochs")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Promotion Mounts\\Felborn Cormaera")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Blizzard Store Mounts\\Gigantic Grrloc")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Blizzard Store Mounts\\Grandiose Grrloc")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Blizzard Store Mounts\\Grizzly Hills Packmaster")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Blizzard Store Mounts\\Herald of Sa'bak")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Blizzard Store Mounts\\Lana'thel's Crimson Cascade")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Promotion Mounts\\Lightwing Dragonhawk")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Blizzard Store Mounts\\Prophet's Great Raven")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Blizzard Store Mounts\\Sha-Warped Cloud Serpent")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Blizzard Store Mounts\\Sha-Warped Riding Tiger")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Blizzard Store Mounts\\Timbered Sky Snake")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Blizzard Store Mounts\\Trader's Gilded Brutosaur")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Promotion Mounts\\Voidwing Dragonhawk")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Achievement Mounts\\Slatestone Ramolith")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Dropped Mounts\\Alunira")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Dropped Mounts\\Ascendant Skyrazor")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Dropped Mounts\\Beledar's Spawn")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Dropped Mounts\\The Big G")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Dropped Mounts\\Blackwater Bonecrusher")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Dropped Mounts\\Dauntless Imperial Lynx")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Dropped Mounts\\Machine Defense Unit 1-11")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Dropped Mounts\\Ol' Mole Rufus")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Dropped Mounts\\Personalized Goblin S.C.R.A.P.per")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Dropped Mounts\\Prototype A.S.M.R.")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Dropped Mounts\\Salvaged Goblin Gazillionaire's Flying Machine")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Dropped Mounts\\Sureki Skyrazor")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Dropped Mounts\\Unbound Star-Eater")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Dropped Mounts\\Venture Co-ordinator")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Dropped Mounts\\Violet Goblin Shredder")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Dropped Mounts\\Void-Scarred Lynx")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Dropped Mounts\\Wick")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Algarian Stormrider")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Brown-Furred Spiky Bakar")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Micellaneous Mounts\\Coldflame Cormaera")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Promotion Mounts\\Coral-Stalker Waveray")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Emerald Snail")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Hand of Reshkigaal")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Highlands Gobbler")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Keg Leg's Radiant Crocolisk")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Dropped Mounts\\Love Witch's Sweeper")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Molten Cormaera")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Pearlescent Butterfly")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Prized Turkey")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Plunderlord's Golden Crocolisk")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Ruby Butterfly")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Aquatic Mounts\\Trading Post Mounts\\Savage Crimson Battle Turtle")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Savage Ebony Battle Turtle")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Spotted Black Riding Goat")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Dropped Mounts\\Spring Butterfly")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Spring Harvesthog")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Thrayir, Eyes of the Siren")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Voidfire Deathcycle")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Micellaneous Mounts\\Void-Scarred Pack Mother")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Profession Mounts\\Crowd Pummeler 2-30")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Profession Mounts\\Kah, Legend of the Deep")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\PVP Mounts\\Forged Gladiator's Fel Bat")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\PVP Mounts\\Hooktalon")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\PVP Mounts\\Plunderlord's Midnight Crocolisk")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\PVP Mounts\\Polly Roger")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\PVP Mounts\\Royal Seafeather")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Underwater Mounts\\PVP Mounts\\Silver Tidestallion")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Quest Mounts\\Curious Slateback")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Quest Mounts\\Darkfuse Spy-Eye")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Quest Mounts\\Delver's Dirigible")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Quest Mounts\\Delver's Dirigible Customization Options")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Quest Mounts\\Delver's Gob-Trotter")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Quest Mounts\\K'arroc Swiftwing")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Quest Mounts\\Royal Voidwing")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Quest Mounts\\Siesbarg")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Quest Mounts\\Stonevault Mechsuit")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Reputation Mounts\\Aquamarine Swarmite")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Reputation Mounts\\Bilgewater Bombardier")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Reputation Mounts\\Blackwater Shredder Deluxe Mk 2")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Reputation Mounts\\Blue Barry")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Reputation Mounts\\Bronze Goblin Waveshredder")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Reputation Mounts\\Crimson Armored Growler")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Reputation Mounts\\Crimson Mudnose")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Reputation Mounts\\Cyan Glowmite")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Reputation Mounts\\Darkfuse Chompactor")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Reputation Mounts\\Darkfuse Demolisher")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Reputation Mounts\\Ferocious Jawcrawler")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Reputation Mounts\\Flarendo the Furious")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Reputation Mounts\\Heritage Undercrawler")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Reputation Mounts\\Mean Green Flying Machine")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Reputation Mounts\\Ochre Delivery Rocket")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Reputation Mounts\\Radiant Imperial Lynx")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Reputation Mounts\\Royal Court Undercrawler")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Reputation Mounts\\Shackled Shadow")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Reputation Mounts\\Shale Ramolith")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Reputation Mounts\\Smoldering Cinderbee")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Reputation Mounts\\Soaring Meaderbee")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Reputation Mounts\\Steamwheedle Supplier")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Reputation Mounts\\Thunderdrum Misfire")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Reputation Mounts\\The Topskimmer Special")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Reputation Mounts\\Vermillion Imperial Lynx")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Reputation Mounts\\Violet Armored Growler")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Reputation Mounts\\Widow's Undercrawler")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Vendor Mounts\\Amani Hunting Bear")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Vendor Mounts\\Asset Advocator")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Vendor Mounts\\Chrono Corsair")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Vendor Mounts\\Corruption of the Aspects")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Vendor Mounts\\Crimson Lupine")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Vendor Mounts\\Innovation Investigator")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Vendor Mounts\\Lavender K'arroc")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Vendor Mounts\\Margin Manipulator")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Vendor Mounts\\Retrained Skyrazor")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Vendor Mounts\\Sandy Shalewing")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Ground Mounts\\Vendor Mounts\\Snowpaw Glimmerfur Prowler")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Vendor Mounts\\Soweezi's Vintage Waveshredder")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Vendor Mounts\\Thundering Ruby Cloud Serpent")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts\\Mounts\\Flying Mounts\\Vendor Mounts\\Timely Buzzbee")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Vendor Mounts\\Wicked Swarmer")
