local GoatQuest=GoatQuest
if not GoatQuest then return end
if UnitFactionGroup("player")~="Horde" then return end
if GQ:DoMutex("PetsMountsHLEGION") then return end
GoatQuest.GuideMenuTier = "TRI"
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Achievement Mounts\\Antoran Gloomhound")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Achievement Mounts\\Defiled Reins")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Achievement Mounts\\Leyfeather Hippogryph")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Achievement Mounts\\Mechanized Lumber Extractor")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Achievement Mounts\\Bleakhoof Ruinstrider")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Achievement Mounts\\Gilded Ravasaur")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Achievement Mounts\\Seabraid Stallion")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Battle Pet Mounts\\Brilliant Direbeak")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Battle Pet Mounts\\Predatory Bloodgazer")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Battle Pet Mounts\\Snowfeather Hunter")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Battle Pet Mounts\\Viridian Sharptalon")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Class Mounts\\Death Knight\\Deathlord's Vilebrood Vanquisher")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Class Mounts\\Demon Hunter\\Slayer's Felbroken Shrieker")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Class Mounts\\Hunter\\Huntmaster's Dire Wolfhawk")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Class Mounts\\Hunter\\Huntmaster's Fierce Wolfhawk")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Class Mounts\\Hunter\\Huntmaster's Loyal Wolfhawk")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Class Mounts\\Mage\\Archmage's Prismatic Disc")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Class Mounts\\Monk\\Ban-Lu, Grandmaster's Companion")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Class Mounts\\Paladin\\Highlord's Golden Charger")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Class Mounts\\Paladin\\Highlord's Valorous Charger")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Class Mounts\\Paladin\\Highlord's Vengeful Charger")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Class Mounts\\Paladin\\Highlord's Vigilant Charger")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Class Mounts\\Priest\\High Priest's Lightsworn Seeker")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Class Mounts\\Rogue\\Shadowblade's Baneful Omen")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Class Mounts\\Rogue\\Shadowblade's Crimson Omen")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Class Mounts\\Rogue\\Shadowblade's Lethal Omen")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Class Mounts\\Rogue\\Shadowblade's Murderous Omen")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Class Mounts\\Shaman\\Farseer's Raging Tempest")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Class Mounts\\Warlock\\Netherlord's Accursed Wrathsteed")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Class Mounts\\Warlock\\Netherlord's Brimstone Wrathsteed")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Class Mounts\\Warlock\\Netherlord's Chaotic Wrathsteed")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Class Mounts\\Warrior\\Battlelord's Bloodthirsty War Wyrm")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Class Mounts\\Demon Hunter\\Felsaber")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Blizzard Store Mounts\\Luminous Starseeker")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Blizzard Store Mounts\\Orgrimmar Interceptor")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Blizzard Store Mounts\\Shu-zen, the Divine Sentinel")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Blizzard Store Mounts\\Stormwind Skychaser")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Dropped Mounts\\Abyss Worm")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Dropped Mounts\\Acid Belcher")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Dropped Mounts\\Antoran Charhound")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Dropped Mounts\\Biletooth Gnasher")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Dropped Mounts\\Crimson Slavermaw")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Dropped Mounts\\Darkspore Mana Ray")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Dropped Mounts\\Felglow Mana Ray")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Dropped Mounts\\Lambent Mana Ray")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Dropped Mounts\\Living Infernal Core")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Dropped Mounts\\Fiendish Hellfire Core")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Dropped Mounts\\Scintillating Mana Ray")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Dropped Mounts\\Smoldering Ember Wyrm")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Dropped Mounts\\Vibrant Mana Ray")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Dropped Mounts\\Vile Fiend")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Dropped Mounts\\Lucid Nightmare")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Dropped Mounts\\Maddened Chaosrunner")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Dropped Mounts\\Midnight's Eternal Reins")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Dropped Mounts\\Shackled Ur'zul")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Long-Forgotten Hippogryph")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Riddler's Mind-Worm")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Brawler's Burly Basilisk")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Fathom Dweller")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Ratstallion")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Player vs. Player Mounts\\Cruel Gladiator's Storm Dragon")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Player vs. Player Mounts\\Dominant Gladiator's Storm Dragon")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Player vs. Player Mounts\\Fearless Gladiator's Storm Dragon")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Player vs. Player Mounts\\Ferocious Gladiator's Storm Dragon")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Player vs. Player Mounts\\Fierce Gladiator's Storm Dragon")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Player vs. Player Mounts\\Vindictive Gladiator's Storm Dragon")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Player vs. Player Mounts\\Ivory Hawkstrider")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Player vs. Player Mounts\\Prestigious Azure Courser")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Player vs. Player Mounts\\Prestigious Bronze Courser")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Player vs. Player Mounts\\Prestigious Forest Courser")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Player vs. Player Mounts\\Prestigious Ivory Courser")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Player vs. Player Mounts\\Prestigious Midnight Courser")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Player vs. Player Mounts\\Prestigious Royal Courser")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Player vs. Player Mounts\\Prestigious War Wolf")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Player vs. Player Mounts\\Vicious War Bear")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Player vs. Player Mounts\\Vicious War Fox")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Player vs. Player Mounts\\Vicious War Scorpion")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Player vs. Player Mounts\\Vicious War Trike")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Player vs. Player Mounts\\Vicious War Turtle")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Player vs. Player Mounts\\Vicious Warstrider")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Aquatic Mounts\\Profession Mounts\\Pond Nettle")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Profession Mounts\\Brinedeep Bottom-Feeder")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Profession Mounts\\Great Northern Elderhorn")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Profession Mounts\\Spirit of Eche'ro")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Profession Mounts\\Steelbound Devourer")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Quest Mounts\\Llothien Prowler")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Reputation Mounts\\Arcanist's Manasaber")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Reputation Mounts\\Cloudwing Hippogryph")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Reputation Mounts\\Leywoven Flying Carpet")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Reputation Mounts\\Lightforged Warframe")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Reputation Mounts\\Valarjar Stormwing")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Reputation Mounts\\Amethyst Ruinstrider")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Reputation Mounts\\Avenging Felcrusher")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Reputation Mounts\\Beryl Ruinstrider")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Reputation Mounts\\Blessed Felcrusher")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Reputation Mounts\\Cerulean Ruinstrider")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Reputation Mounts\\Glorious Felcrusher")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Reputation Mounts\\Highmountain Elderhorn")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Reputation Mounts\\Russet Ruinstrider")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Reputation Mounts\\Sable Ruinstrider")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Reputation Mounts\\Umber Ruinstrider")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Reputation Mounts\\Wild Dreamrunner")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Aquatic Mounts\\Vendor Mounts\\Darkwater Skate")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Vendor Mounts\\Yu'lei, Daughter of Jade")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Vendor Mounts\\Arcadian War Turtle")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Vendor Mounts\\Bloodfang Widow")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\World Event Mounts\\Darkmoon Dirigible")
