local GoatQuest=GoatQuest
if not GoatQuest then return end
if GQ:DoMutex("PetsMountsCSHADOW") then return end
GQ.BETASTART()
GQ.BETAEND()
GoatQuest.GuideMenuTier = "TRI"
GQ.BETASTART()
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Achievement Mounts\\Rampart Screecher")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Achievement Mounts\\Silky Shimmermoth")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Achievement Mounts\\Sintouched Deathwalker")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Achievement Mounts\\Voracious Gorger")
GQ.BETAEND()
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Blizzard Store Mounts\\Lucky Yun")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Blizzard Store Mounts\\Nether-Gorged Greatwyrm")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Covenant Mounts\\Kyrian Mounts\\Gruesome Flayedwing (Kyrian)")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Covenant Mounts\\Kyrian Mounts\\Silvertip Dredwing (Kyrian)")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Covenant Mounts\\Kyrian Mounts\\Eternal Phalynx of Courage")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Covenant Mounts\\Kyrian Mounts\\Eternal Phalynx of Humility")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Covenant Mounts\\Kyrian Mounts\\Eternal Phalynx of Loyalty")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Covenant Mounts\\Kyrian Mounts\\Eternal Phalynx of Purity")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Covenant Mounts\\Kyrian Mounts\\Pale Acidmaw (Kyrian)")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Covenant Mounts\\Kyrian Mounts\\Phalynx of Courage")
GQ.BETAEND()
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Covenant Mounts\\Kyrian Mounts\\Phalynx of Purity")
GQ.BETAEND()
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Covenant Mounts\\Necrolord Mounts\\Dauntless Duskrunner (Necrolord)")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Covenant Mounts\\Necrolord Mounts\\Gruesome Flayedwing (Necrolord)")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Covenant Mounts\\Necrolord Mounts\\Predatory Plagueroc")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Covenant Mounts\\Necrolord Mounts\\Silvertip Dredwing (Necrolord)")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Covenant Mounts\\Necrolord Mounts\\Armored Bonehoof Tauralus")
GQ.BETAEND()
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Covenant Mounts\\Necrolord Mounts\\Armored Plaguerot Tauralus")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Covenant Mounts\\Necrolord Mounts\\Armored War-Bred Tauralus")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Covenant Mounts\\Necrolord Mounts\\Bonehoof Tauralus")
GQ.BETAEND()
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Covenant Mounts\\Necrolord Mounts\\Pale Acidmaw (Necrolord)")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Covenant Mounts\\Necrolord Mounts\\Plaguerot Tauralus")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Covenant Mounts\\Necrolord Mounts\\War-Bred Tauralus")
GQ.BETAEND()
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Covenant Mounts\\Night Fae Mounts\\Vibrant Flutterwing")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Covenant Mounts\\Night Fae Mounts\\Dreamlight Runestag")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Covenant Mounts\\Night Fae Mounts\\Enchanted Dreamlight Runestag")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Covenant Mounts\\Night Fae Mounts\\Enchanted Shadeleaf Runestag")
GQ.BETAEND()
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Covenant Mounts\\Night Fae Mounts\\Enchanted Winterborn Runestag")
GQ.BETAEND()
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Covenant Mounts\\Night Fae Mounts\\Shadeleaf Runestag")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Covenant Mounts\\Night Fae Mounts\\Umbral Scythehorn")
GQ.BETAEND()
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Covenant Mounts\\Night Fae Mounts\\Wild Glimmerfur Prowler")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Covenant Mounts\\Night Fae Mounts\\Winterborn Runestag")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Covenant Mounts\\Venthyr Mounts\\Dauntless Duskrunner (Venthyr)")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Covenant Mounts\\Venthyr Mounts\\Gruesome Flayedwing (Venthyr)")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Covenant Mounts\\Venthyr Mounts\\Horrid Dredwing")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Covenant Mounts\\Venthyr Mounts\\Silvertip Dredwing (Venthyr)")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Covenant Mounts\\Venthyr Mounts\\Battle Gargon Silessa")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Covenant Mounts\\Venthyr Mounts\\Battle Gargon Vrednic")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Covenant Mounts\\Venthyr Mounts\\Crypt Gargon")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Covenant Mounts\\Venthyr Mounts\\Desire's Battle Gargon")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Covenant Mounts\\Venthyr Mounts\\Gravestone Battle Armor")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Covenant Mounts\\Venthyr Mounts\\Hopecrusher Gargon")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Covenant Mounts\\Venthyr Mounts\\Pale Acidmaw (Venthyr)")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Covenant Mounts\\Venthyr Mounts\\Sinfall Gargon")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Dropped Mounts\\Callow Flayedwing")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Dropped Mounts\\Endmire Flyer")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Dropped Mounts\\Hulking Deathroc")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Dropped Mounts\\Marrowfang")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Dropped Mounts\\Shimmermist Runner")
GQ.BETAEND()
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Dropped Mounts\\Swift Gloomhoof")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Dropped Mounts\\Arboreal Gulper")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Dropped Mounts\\Battle-Bound Warhound")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Dropped Mounts\\Blisterback Bloodtusk")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Dropped Mounts\\Gorespine")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Dropped Mounts\\Loyal Gorger")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Dropped Mounts\\Mawsworn Soulhunter")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Dropped Mounts\\Spinemaw Gladechewer")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Ascended Skymane")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Bulbous Necroray")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Chittering Animite")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Highwind Darkmane")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Infested Necroray")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Pestilent Necroray")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Silverwind Larion")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Sundancer")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Wildseed Cradle")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Bound Shadehound")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Corridor Creeper")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Darkwarren Hardshell")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Sinrunner Blanchy")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Warstitched Darkhound")
GQ.BETAEND()
GQ.BETASTART()
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Reputation Mounts\\The Wild Hunt Mounts\\Amber Ardenmoth")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Reputation Mounts\\The Undying Army\\Colossal Slaughterclaw")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Reputation Mounts\\The Wild Hunt Mounts\\Duskflutter Ardenmoth")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Reputation Mounts\\The Ascended Mounts\\Gilded Prowler")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Reputation Mounts\\Court of Harvestors Mounts\\Court Sinrunner")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Reputation Mounts\\The Avowed Mounts\\Inquisition Gargon")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Reputation Mounts\\The Undying Army\\Lurid Bloodtusk")
GQ.BETAEND()
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Amber Shardhide")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Ardenweald Wilderling")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Ascendant's Aquilon")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Autumnal Wilderling")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Beryl Shardhide")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Cartel Master's Gearglider")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Crimson Shardhide")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Darkmaul")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Dusklight Razorwing")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Elysian Aquilon")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Fallen Charger")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Fierce Razorwing")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Foresworn Aquilon")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Garnet Razorwing")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Hand of Bahmethra")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Lord of the Corpseflies")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Maldraxxian Corpsefly")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Obsidian Gravewing")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Regal Corpsefly")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Sanctum Gloomcharger")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Sinfall Gravewing")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Soaring Razorwing")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Soulbound Gloomcharger")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Summer Wilderling")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Tamed Mauler")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Undying Darkhound")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Vengeance")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Vicious War Gorm (Alliance)")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Vicious War Gorm (Horde)")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Wandering Arden Doe")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Wild Hunt Legsplitter")
GQ.BETAEND()
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Patient Bufonid")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Bronze Helicid")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Aquatic Mounts\\Miscellaneous Mounts\\Deepstar Aurelid")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Bronzewing Vespoid")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Buzz")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Forged Spiteflyer")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Adorned Vombata")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Deathrunner")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Genesis Crawler")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Pale Regal Cervid")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Raptora Swooper")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Russet Bufonid")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Sundered Zerethsteed")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Tarachnid Creeper")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Vespoid Flutterer")
