local GoatQuest=GoatQuest
if not GoatQuest then return end
if UnitFactionGroup("player")~="Horde" then return end
if GQ:DoMutex("HunterPetHLEGION") then return end
GoatQuest.GuideMenuTier = "TRI"
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Beast Mastery Exotic Pets\\Clefthooves\\Saddled Greater Clefthooves\\Red Saddled Greater Clefthoof")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Beast Mastery Exotic Pets\\Core Hounds\\Green Core Hound")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Beast Mastery Exotic Pets\\Core Hounds\\Orange Core Hound")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Beast Mastery Exotic Pets\\Core Hounds\\Yellow Core Hound")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Beast Mastery Exotic Pets\\Devilaurs\\Black Armored Devilsaur")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Beast Mastery Exotic Pets\\Silithids\\Sandreavers\\Orange Sandreaver")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Beast Mastery Exotic Pets\\Silithids\\Sandreavers\\Pink Sandreaver")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Beast Mastery Exotic Pets\\Silithids\\Sandreavers\\Purple Sandreaver")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Beast Mastery Exotic Pets\\Silithids\\Sandreavers\\Striped Orange Sandreaver")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Beast Mastery Exotic Pets\\Silithids\\Sandreavers\\Striped Purple Sandreaver")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Beast Mastery Exotic Pets\\Silithids\\Sandreavers\\Striped Yellow Sandreaver")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Beast Mastery Exotic Pets\\Silithids\\Sandreavers\\Yellow Sandreaver")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Beast Mastery Exotic Pets\\Spirit Beasts\\Spirit Elderhorn")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Beast Mastery Exotic Pets\\Spirit Beasts\\Mana Sabers\\Blue Mana Saber")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Beast Mastery Exotic Pets\\Spirit Beasts\\Mana Sabers\\Indigo Mana Saber")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Beast Mastery Exotic Pets\\Spirit Beasts\\Mana Sabers\\Purple Mana Saber")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Beast Mastery Exotic Pets\\Water Striders\\Coral Water Strider")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Beast Mastery Exotic Pets\\Worms\\Jormungars\\Bright Green Jormungar")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Basilisks\\Spiny Basilisks\\Fel-Green Spiny Basilisk")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Basilisks\\Spiny Basilisks\\Gray Spiny Basilisk")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Basilisks\\Spiny Basilisks\\Olive-Green Spiny Basilisk")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Basilisks\\Spiny Basilisks\\Orange Spiny Basilisk")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Basilisks\\Spiny Basilisks\\Purple Spiny Basilisk (Legion)")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Bears\\Dark Bear")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Bears\\Dark Brown Bear")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Bears\\Diseased Dark Bear")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Bears\\Diseased Dark Brown Bear")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Bears\\Diseased Gray Bear")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Bears\\Diseased Tan Bear")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Bears\\Diseased White Bear")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Bears\\Gray Bear")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Bears\\Old Model Bears\\Old Model Black Bear")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Bears\\Old Model Bears\\Old Model Brown Bear")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Bears\\Old Model Bears\\Old Model Dark Brown Bear")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Bears\\Old Model Bears\\Old Model Diseased Black Bear")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Bears\\Old Model Bears\\Old Model Diseased Brown Bear")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Bears\\Old Model Bears\\Old Model Diseased Dark Brown Bear")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Bears\\Old Model Bears\\Old Model Diseased Gray Bear")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Bears\\Old Model Bears\\Old Model Diseased White Bear")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Bears\\Old Model Bears\\Old Model Gray Bear")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Bears\\Old Model Bears\\Old Model White Bear")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Bears\\Tan Bear")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Bears\\White Bear")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Cats\\Nightsabers\\Black Nightsaber")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Cats\\Nightsabers\\Brown Nightsaber")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Cats\\Nightsabers\\Gray Nightsaber")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Cats\\Nightsabers\\Pale Nightsaber")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Boars\\Greater Boars\\Arcane Purple Greater Boar")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Boars\\Greater Boars\\Dark Brown Greater Boar")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Marsuul\\Blue and Orange Marsuul")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Marsuul\\Fel-Grey Marsuul")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Marsuul\\Orange and Green Marsuul")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Marsuul\\Pale Blue Marsuul")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Marsuul\\Purple and Green Marsuul")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Marsuul\\Void-Touched Marsuul")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Oxen\\Musken\\Black Musken")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Oxen\\Musken\\Brown Musken")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Oxen\\Musken\\White Musken")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Oxen\\Shoveltusks\\Brown Shoveltusk")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Oxen\\Shoveltusks\\Dark Shoveltusk")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Oxen\\Shoveltusks\\Pale Shoveltusk")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Oxen\\Shoveltusks\\Red Shoveltusk")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Oxen\\Yaks\\Black Yak")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Oxen\\Yaks\\Brown Yak")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Oxen\\Yaks\\Gray Yak")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Oxen\\Yaks\\Tan Yak")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Oxen\\Yaks\\White Yak")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Panthara\\Dark Teal Panthara")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Panthara\\Fel Green Panthara")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Panthara\\Indigo Panthara")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Panthara\\Purple-Yellow Panthara")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Panthara\\Silver-Blue Panthara")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Panthara\\Yellow-Green Panthara")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Raptors\\Falcosaurs\\Black and Red Falcosaur")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Raptors\\Falcosaurs\\Orange and Turquoise Falcosaur")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Raptors\\Falcosaurs\\Purple and Green Falcosaur")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Raptors\\Falcosaurs\\Silver and Gray Falcosaur")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Scalehides\\Kodos\\Furry Brown Kodo")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Scalehides\\Kodos\\Green-Beige Kodo")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Scalehides\\Kodos\\Yellow Kodo")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Scalehides\\Mushan\\Blue Mushan")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Scalehides\\Mushan\\Dark Mushan")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Scalehides\\Mushan\\Green Mushan")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Scalehides\\Mushan\\Pale Mushan")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Scalehides\\Mushan\\Tan Mushan")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Scalehides\\Stegodons\\Beige Stegodon")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Scalehides\\Stegodons\\Black Stegodon")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Scalehides\\Stegodons\\Blue Stegodon")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Scalehides\\Stegodons\\Dark Green Stegodon")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Scalehides\\Stegodons\\Light Green Stegodon")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Scalehides\\Stegodons\\Red Stegodon")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Stags\\Does\\Dark Brown Doe")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Stags\\Does\\Gray Doe")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Stags\\Does\\Orange Doe")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Stags\\Does\\Puce Doe")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Stags\\Does\\White Doe")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Stags\\Greater Stags\\Dark Brown Greater Stag")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Stags\\Greater Stags\\Gray Greater Stag")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Stags\\Greater Stags\\Orange Greater Stag")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Stags\\Greater Stags\\Puce Greater Stag")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Stags\\Greater Stags\\Patterned White Greater Stag")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Stags\\Elderhorns\\Beige Elderhorn")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Stags\\Elderhorns\\Black Elderhorn")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Stags\\Elderhorns\\Silver Elderhorn")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Stags\\Elderhorns\\Tan Elderhorn")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Stags\\Argus Talbuks\\Blue Spiny Talbuk with Backswept Horns")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Stags\\Argus Talbuks\\Blue Spiny Talbuk with Side Horns")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Stags\\Argus Talbuks\\Brown Spiny Talbuk with Backswept Horns")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Stags\\Argus Talbuks\\Brown Spiny Talbuk with Side Horns")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Stags\\Argus Talbuks\\Fel Brown Talbuk with Backswept Horns")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Stags\\Argus Talbuks\\Fel Brown Talbuk with Side Horns")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Stags\\Argus Talbuks\\Fel Maroon Talbuk with Backswept Horns")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Stags\\Argus Talbuks\\Fel Maroon Talbuk with Side Horns")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Stags\\Argus Talbuks\\Orange Talbuk with Backswept Horns")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Stags\\Argus Talbuks\\Purple Talbuk With Side Horns")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Stags\\Argus Talbuks\\Purple With Backswept Horns")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Stags\\Argus Talbuks\\Red-Brown Talbuk with Backswept Horns")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Stags\\Argus Talbuks\\Teal-Grey Talbuk with Backswept Horns")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Stags\\Argus Talbuks\\White Talbuk with Backswept Horns")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Wolves\\Dire Worgs\\Dark Gray Dire Worg")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Wolves\\Dire Worgs\\Light Gray Dire Worg")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Wolves\\Dire Worgs\\Tan Dire Worg")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Wolves\\Maned Wolves\\Auburn Maned Wolf")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Wolves\\Maned Wolves\\Dark Brown Maned Wolf")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Ground Pets\\Wolves\\Scarred Worgs\\Battle-Scarred Runed Worg")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Flying Pets\\Bats\\Greater Bats\\Green Greater Bat")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Flying Pets\\Birds of Prey\\Eagles\\Brown Eagle (Legion)")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Flying Pets\\Birds of Prey\\Eagles\\Dark Brown Eagle")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Flying Pets\\Birds of Prey\\Eagles\\Light Brown Eagle")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Flying Pets\\Birds of Prey\\Eagles\\White Eagle")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Flying Pets\\Birds of Prey\\Warden Owls\\Brown Warden Owl")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Flying Pets\\Birds of Prey\\Warden Owls\\Dark Warden Owl")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Flying Pets\\Birds of Prey\\Warden Owls\\Pale Warden Owl")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Flying Pets\\Birds of Prey\\Warden Owls\\Purple Warden Owl")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Flying Pets\\Carrion Birds\\Ravens\\Raven")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Flying Pets\\Feathermanes\\Grand Hippogryphs\\Arcane Purple Grand Hippogryph")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Flying Pets\\Feathermanes\\Grand Hippogryphs\\Blue and Gold Grand Hippogryph")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Flying Pets\\Feathermanes\\Grand Hippogryphs\\Green and Red Grand Hippogryph")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Flying Pets\\Feathermanes\\Gryphons\\Black Gryphon")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Flying Pets\\Feathermanes\\Gryphons\\Brown Gryphon")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Flying Pets\\Feathermanes\\Gryphons\\White Gryphon")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Flying Pets\\Feathermanes\\Hippogryphs\\Blue Hippogryph")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Flying Pets\\Feathermanes\\Hippogryphs\\Brown and White Hippogryph")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Flying Pets\\Feathermanes\\Hippogryphs\\Dark Hippogryph")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Flying Pets\\Feathermanes\\Hippogryphs\\Fel Green Hippogryph")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Flying Pets\\Feathermanes\\Hippogryphs\\Pale Hippogryph (Rare Spawn)")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Flying Pets\\Feathermanes\\Hippogryphs\\Purple Hippogryph")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Flying Pets\\Feathermanes\\Owlcats\\Black Owlcat")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Flying Pets\\Feathermanes\\Owlcats\\Brown Owlcat")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Flying Pets\\Feathermanes\\Owlcats\\Gray-Brown Owlcat")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Flying Pets\\Feathermanes\\Owlcats\\Silver-Gray Owlcat")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Flying Pets\\Feathermanes\\Wind Riders\\Blue Wind Rider (Rare Spawn)")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Flying Pets\\Feathermanes\\Wind Riders\\Brown Wind Rider")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Flying Pets\\Feathermanes\\Wind Riders\\Green Wind Rider")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Flying Pets\\Feathermanes\\Wolfhawks\\Blue Wolfhawk")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Flying Pets\\Feathermanes\\Wolfhawks\\Brown Wolfhawk")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Flying Pets\\Feathermanes\\Wolfhawks\\Green Wolfhawk")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Flying Pets\\Serpents\\Mana Wyrms\\Blue-Silver Mana Wyrm")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Flying Pets\\Serpents\\Mana Wyrms\\Green Mana Wyrm")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Flying Pets\\Serpents\\Mana Wyrms\\Peach-Silver Mana Wyrm")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Flying Pets\\Serpents\\Mana Wyrms\\Ruby Mana Wyrm")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Flying Pets\\Serpents\\Mana Wyrms\\Violet Mana Wyrm")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Flying Pets\\Nether Rays\\Mana Rays\\Blue and Orange Mana Ray")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Flying Pets\\Nether Rays\\Mana Rays\\Fel Gray-Plum Mana Ray")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Flying Pets\\Nether Rays\\Mana Rays\\Fel Red Mana Ray")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Flying Pets\\Nether Rays\\Mana Rays\\Magenta Mana Ray")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Flying Pets\\Nether Rays\\Mana Rays\\Purple Mana Ray")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Flying Pets\\Nether Rays\\Mana Rays\\Teal Mana Ray")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Flying Pets\\Wasps\\Dire Wasps\\Nightmare Dire Wasp")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Flying Pets\\Wasps\\Fireflies\\Yellow Glowing Purple Firefly")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Flying Pets\\Wind Serpents\\Spiked Wind Serpents\\Gray and Green Spiked Wind Serpent")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Mechanical Pets\\Electric Sheep\\Robotic Sheep")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Mechanical Pets\\Iron Scorpions\\Blue Iron Scorpion")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Mechanical Pets\\Iron Scorpions\\Green-Gold Iron Scorpion")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Mechanical Pets\\Iron Scorpions\\Red-Gray Iron Scorpion")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Mechanical Pets\\Iron Scorpions\\Teal Iron Scorpion")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Mechanical Pets\\Mechanical Axebeaks\\Mechanical Axebeak")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Mechanical Pets\\Mechanical Rabbits\\Robotic Rabbit")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Mechanical Pets\\Mechanical Spiders\\Copper-Gray Mechanical Spider")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Mechanical Pets\\Mechanical Spiders\\Gold Mechanical Spider")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Mechanical Pets\\Mechanical Spiders\\Gray-Bronze Mechanical Spider")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Mechanical Pets\\Mechanical Squirrel\\Mechanical Squirrel")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Mechanical Pets\\Mechanostriders\\Blue-Purple Mechanostrider")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Mechanical Pets\\Mechanostriders\\Matte-Gray Mechanostrider")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Mechanical Pets\\Mechanostriders\\Red-Blue Mechanostrider")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Mechanical Pets\\Mechanowolves\\Black Mechanowolf")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Mechanical Pets\\Mechanowolves\\Blue Mechanowolf")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Mechanical Pets\\Mechanowolves\\Green Mechanowolf")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Mechanical Pets\\Mechanowolves\\Red Mechanowolf")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Mechanical Pets\\Robotic Chickens\\Robot Chicken")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Mechanical Pets\\Robotic Gorillas\\Robotic Gorilla")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Water Pets\\Crabs\\Spiked Crabs\\Red-Tinged Steel Blue Spiked Crab")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Water Pets\\Turtles\\Spiked Dragon Turtles\\Camo Spiked Dragon Turtle")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Water Pets\\Turtles\\Spiked Dragon Turtles\\Red Spiked Dragon Turtle")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Hunter Pets\\Legion Pets\\Water Pets\\Turtles\\Stone Dragon Turtles\\Stone Dragon Turtle")
