local GoatQuest=GoatQuest
if not GoatQuest then return end
if UnitFactionGroup("player")~="Alliance" then return end
if GQ:DoMutex("PetsMountsA") then return end
GoatQuest.GuideMenuTier = "TRI"
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Paladin\\Warhorse")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Paladin\\Charger")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Paladin\\Exarch's Elekk")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Paladin\\Great Exarch's Elekk")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Warlock\\Felsteed")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Warlock\\Dreadsteed")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Argent Tournament Mounts\\Argent Warhorse")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Argent Tournament Mounts\\Darnassus Mounts")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Argent Tournament Mounts\\Exodar Mounts")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Argent Tournament Mounts\\Gnomeregan Mounts")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Argent Tournament Mounts\\Ironforge Mounts")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Argent Tournament Mounts\\Quel'dorei Steed")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Argent Tournament Mounts\\Stormwind Mounts")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Dailies Mounts\\Darkmoon Faire Mounts")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Dailies Mounts\\White Polar Bear")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Dailies Mounts\\Winterspring Frostsaber")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Dropped Mounts\\Grey Riding Camel")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Dungeon Mounts\\Amani Battle Bear")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Dungeon Mounts\\Raven Lord")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Dungeon Mounts\\Rivendare's Deathcharger")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Dungeon Mounts\\Swift White Hawkstrider")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Dungeon Mounts\\Swift Zulian Panther and Armored Razzashi Raptor")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Dungeon Mounts\\Wooly Mammoth")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Event Mounts\\Brewfest\\Brewfest Rams")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Event Mounts\\Brewfest\\Great Brewfest Kodo")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Event Mounts\\Darkmoon Faire\\Moonfang")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Event Mounts\\Love is in the Air\\Swift Lovebird")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Event Mounts\\Noblegarden\\Swift Springstrider")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Faction Mounts\\Elekk Mounts")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Faction Mounts\\Horse Mounts")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Faction Mounts\\Mechanostrider Mounts")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Faction Mounts\\Ram Mounts")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Faction Mounts\\Tiger Mounts")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Player vs. Player Mounts\\Black Battlestrider")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Player vs. Player Mounts\\Black War Bear")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Player vs. Player Mounts\\Black War Elekk")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Player vs. Player Mounts\\Black War Mammoth")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Player vs. Player Mounts\\Black War Ram")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Player vs. Player Mounts\\Black War Steed")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Player vs. Player Mounts\\Black War Tiger")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Player vs. Player Mounts\\Dark War Talbuk")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Player vs. Player Mounts\\Dark Riding Talbuk")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Player vs. Player Mounts\\Stormpike Battle Charger")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Profession Mounts\\Archaeology\\Fossilized Raptor")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Profession Mounts\\Archaeology\\Ultramarine Qiraji Battle Tank")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Profession Mounts\\Engineering\\Mekgineer's Chopper")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Raid Mounts\\Flametalon of Alysrazor")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Raid Mounts\\Fiery Warhorse")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Raid Mounts\\Grand Black War Mammoth")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Raid Mounts\\Qiraji Mounts")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Reputation Mounts\\Camel Mounts")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Reputation Mounts\\Golden King")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Reputation Mounts\\Ice Mammoth & Grand Ice Mammoth")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Reputation Mounts\\Mountain Horse Mounts")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Reputation Mounts\\Spectral Steed")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Reputation Mounts\\Talbuk Mounts")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Trading Card Mounts\\Big Battle Bear")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Trading Card Mounts\\Magic Rooster")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Trading Card Mounts\\Riding Turtle")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Trading Card Mounts\\Savage Raptor")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Trading Card Mounts\\Spectral Tiger")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Trading Card Mounts\\Swift Shorestrider")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Trading Card Mounts\\White Riding Camel")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Trading Card Mounts\\Wooly White Rhino")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Unavailable Mounts\\Amani War Bear")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Unavailable Mounts\\Ancient Frostsaber")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Unavailable Mounts\\Black Nightsaber")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Unavailable Mounts\\Black Qiraji Battle Tank")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Unavailable Mounts\\Black Ram")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Unavailable Mounts\\Brewfest Ram")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Unavailable Mounts\\Crusader's White Warhorse")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Unavailable Mounts\\Frost Ram")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Unavailable Mounts\\Icy Blue Mechanostrider Mod A")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Unavailable Mounts\\Palomino")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Unavailable Mounts\\Swift Alliance Steed")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Unavailable Mounts\\Swift Razzashi Raptor")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Unavailable Mounts\\Swift Zulian Tiger")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Unavailable Mounts\\White Mechanostrider Mod B")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Unavailable Mounts\\White Stallion")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Vendor Mounts\\Armored Brown Bear")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Vendor Mounts\\Traveler's Tundra Mammoth")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Achievement Mounts\\Albino Drake")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Achievement Mounts\\Bloodbathed Frostbrood Vanquisher")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Achievement Mounts\\Blue Dragonhawk")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Achievement Mounts\\Corrupted Fire Hawk")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Achievement Mounts\\Drake of the East Wind")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Achievement Mounts\\Flameward Hippogryph")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Achievement Mounts\\Green Proto-Drake")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Achievement Mounts\\Icebound Frostbrood Vanquisher")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Achievement Mounts\\Ironbound Proto-Drake")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Achievement Mounts\\Red Proto-Drake")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Achievement Mounts\\Rusted Proto-Drake")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Achievement Mounts\\Twilight Harbinger")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Achievement Mounts\\Violet Proto-Drake")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Achievement Mounts\\Volcanic Stone Drake")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Argent Tournament Mounts\\Argent Hippogryph")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Argent Tournament Mounts\\Silver Covenant Hippogryph")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Blizzard Store Mounts\\Celestial Steed")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Blizzard Store Mounts\\Heart of the Aspects")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Blizzard Store Mounts\\Iron Skyreaver")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Blizzard Store Mounts\\Swift Windsteed")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Blizzard Store Mounts\\Winged Guardian")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Dropped Mounts\\Phosphorescent Stone Drake")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Dropped Mounts\\Time-Lost Proto-Drake")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Dungeon Mounts\\Blue Drake")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Dungeon Mounts\\Blue Proto-Drake")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Dungeon Mounts\\Bronze Drake")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Dungeon Mounts\\Drake of the North Wind")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Dungeon Mounts\\Vitreous Stone Drake")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Event Mounts\\Love is in the Air\\X-45 Heartbreaker")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Event Mounts\\Hallow's End\\Headless Horseman's Mount")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Event Mounts\\Hallow's End\\Magic Broom")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Obsidian Nightwing")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\X-53 Touring Rocket")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Ground Mounts\\Miscellaneous Mounts\\Swift Zhevra")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Miscellaneous Mounts\\Emerald Hippogryph")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Profession Mounts\\Engineering\\Flying Machine")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Profession Mounts\\Engineering\\Turbo-Charged Flying Machine")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Profession Mounts\\Tailoring\\Flying Carpet")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Profession Mounts\\Tailoring\\Frosty Flying Carpet")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Profession Mounts\\Tailoring\\Magnificent Flying Carpet")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Raid Mounts\\Ashes of Al'ar")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Raid Mounts\\Azure Drake")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Raid Mounts\\Black Drake")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Raid Mounts\\Blazing Drake")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Raid Mounts\\Experiment 12-B")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Raid Mounts\\Invincible")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Raid Mounts\\Life-Binder's Handmaiden")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Raid Mounts\\Mimiron's Head")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Raid Mounts\\Onyxian Drake")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Raid Mounts\\Pureblood Fire Hawk")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Raid Mounts\\Twilight Drake")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Raid Mounts\\Drake of the South Wind")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Reputation Mounts\\Cenarion War Hippogryph")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Reputation Mounts\\Dark Phoenix")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Reputation Mounts\\Drake of the West Wind")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Reputation Mounts\\Netherwing Drakes\\Quests & Dailies")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Reputation Mounts\\Netherwing Drakes\\Netherwing Egg Hunting - Optimized Path")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Reputation Mounts\\Red Drake")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Reputation Mounts\\Riding Nether Ray\\Skyguard Faction Dailies with Pre-Quests")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Trading Card Mounts\\Amani Dragonhawk")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Trading Card Mounts\\Mottled Drake")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Trading Card Mounts\\Blazing Hippogryph")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Trading Card Mounts\\Corrupted Hippogryph")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Trading Card Mounts\\X-51 Nether-Rocket")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Trading Card Mounts\\X-51 Nether-Rocket X-TREME")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Trading Card Mounts\\Feldrake")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Unavailable Mounts\\Black Proto-Drake")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Unavailable Mounts\\Brutal Nether Drake")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Unavailable Mounts\\Cataclysmic Gladiator's Twilight Drake")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Unavailable Mounts\\Deadly Gladiator's Frost Wyrm")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Unavailable Mounts\\Furious Gladiator's Frost Wyrm")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Unavailable Mounts\\Merciless Nether Drake")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Unavailable Mounts\\Relentless Gladiator's Frost Wyrm")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Unavailable Mounts\\Ruthless Gladiator's Twilight Drake")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Unavailable Mounts\\Spectral Gryphon")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Unavailable Mounts\\Swift Nether Drake")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Unavailable Mounts\\Tyrael's Charger")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Unavailable Mounts\\Vengeful Nether Drake")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Unavailable Mounts\\Vicious Gladiator's Twilight Drake")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Unavailable Mounts\\Wrathful Gladiator's Frost Wyrm")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Vendor Mounts\\Armored Snowy Gryphon")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Vendor Mounts\\Gryphons")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Vendor Mounts\\Sandstone Drake")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Flying Mounts\\Vendor Mounts\\Winged Steed of the Ebon Blade")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Aquatic Mounts\\Sea Turtle")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Aquatic Mounts\\Subdued Seahorse")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Aquatic Mounts\\Vashj'ir Seahorse")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Argent Tournament Guides\\Crusader Title Guide\\Draenei Champion Rank")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Argent Tournament Guides\\Crusader Title Guide\\Dwarf Champion Rank")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Argent Tournament Guides\\Crusader Title Guide\\Gnome Champion Rank")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Argent Tournament Guides\\Crusader Title Guide\\Human Champion Rank")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Argent Tournament Guides\\Crusader Title Guide\\Night Elf Champion Rank")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Argent Tournament Guides\\Home Cities Reputation\\The Exodar\\Draenei")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Argent Tournament Guides\\Home Cities Reputation\\Ironforge & Gnomeregan\\Dwarf")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Argent Tournament Guides\\Home Cities Reputation\\Ironforge & Gnomeregan\\Dwarf & Gnome")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Argent Tournament Guides\\Home Cities Reputation\\Ironforge & Gnomeregan\\Gnome")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Argent Tournament Guides\\Home Cities Reputation\\Stormwind\\Human")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Argent Tournament Guides\\Home Cities Reputation\\Darnassus\\Night Elf")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Argent Tournament Guides\\Argent Tournament Grounds Aspirant Rank Dailies")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Argent Tournament Guides\\Argent Tournament Grounds Champion Rank Dailies - Death Knight Only")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Argent Tournament Guides\\Argent Tournament Grounds Champion Rank Dailies - Non-Death Knight Only")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Argent Tournament Guides\\Argent Tournament Grounds Crusader Dailies")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Argent Tournament Guides\\Argent Tournament Grounds Valiant Rank Dailies")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mounts\\Argent Tournament Guides\\Pre-Quests")
GoatQuest:RegisterGuidePlaceholder("Pets & Mounts Guides\\Mount Training")
